import base64
import copy
import io
import math
import os
import time
from typing import Tuple

import numpy as np
import pandas as pd
import requests
import torch
import torch.nn.functional as F
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split
from torch import nn, Tensor
from torch.nn import TransformerEncoder, TransformerEncoderLayer
from torch.optim.lr_scheduler import LambdaLR
from tqdm import tqdm

from balanced_loss import Loss

# pip install numpy pandas requests tqdm torch sklearn

batch_size = 32
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


def get_batch(source: Tuple, i: int) -> Tuple[Tensor, Tensor]:
    """
    Args:
        source: Tensor, shape [full_seq_len, batch_size]
        i: int

    Returns:
        tuple (data, target), where data has shape [seq_len, batch_size] and
        target has shape [seq_len * batch_size]
    """
    x, y = source
    seq_len = min(batch_size, len(x) - 1 - i)
    data = x[i:i + seq_len]
    target = y[i:i + seq_len]
    return data.to(device), target.to(device)


def train_epoch(model: nn.Module, X, y, criterion, optimizer, scheduler, epoch, n_classes) -> None:
    model.train()  # turn on train mode
    total_loss = 0.
    log_interval = 200
    start_time = time.time()

    num_batches = len(X) // batch_size
    for batch, i in enumerate(pbar := tqdm(range(0, X.size(0) - 1, batch_size))):
        data, targets = get_batch((X, y), i)
        output = model(data)
        loss = criterion(output.view(-1, n_classes), targets)
        pbar.set_postfix(loss=loss.item(), lr=scheduler.get_last_lr()[0])
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)
        optimizer.step()
        scheduler.step()

        total_loss += loss.item()
        if batch % log_interval == 0 and batch > 0:
            lr = scheduler.get_last_lr()[0]
            ms_per_batch = (time.time() - start_time) * 1000 / log_interval
            cur_loss = total_loss / log_interval
            ppl = math.exp(cur_loss)
            print(f'| epoch {epoch:3d} | {batch:5d}/{num_batches:5d} batches | '
                  f'lr {lr:02.2f} | ms/batch {ms_per_batch:5.2f} | '
                  f'loss {cur_loss:5.2f} | ppl {ppl:8.2f}')
            total_loss = 0
            start_time = time.time()


def evaluate(model: nn.Module, eval_data: Tuple, criterion, nclasses) -> (float, float, float, float):
    X, y = eval_data
    model.eval()  # turn on evaluation mode
    total_loss = 0.
    tgts, preds = [], []
    with torch.no_grad():
        for i in range(0, X.size(0) - 1, batch_size):
            data, targets = get_batch((X, y), i)
            seq_len = data.size(0)
            # if seq_len != bptt:
            #     src_mask = src_mask[:seq_len, :seq_len]
            output = model(data)
            output_flat = output.view(-1, nclasses)
            predictions = output_flat.argmax(dim=1)
            preds.extend(predictions.tolist())
            tgts.extend(targets.tolist())
            total_loss += seq_len * criterion(output_flat, targets).item()
    tgts = np.array(tgts)
    preds = np.array(preds)
    acc = accuracy_score(tgts, preds)
    f1_micro = f1_score(tgts, preds, average='micro')
    f1_macro = f1_score(tgts, preds, average='macro')
    print(np.unique(preds, return_counts=True))
    print(f1_score(tgts, preds, average=None))
    return total_loss / (len(eval_data) - 1), acc, f1_micro, f1_macro

class TransformerClassifier:

    def __str__(self):
        return 'TransformerClassifier'

    def __init__(self):
        n_features = 75  # embedding dimension
        emsize = 100  # embedding dimension
        d_hid = 200  # dimension of the feedforward network model in nn.TransformerEncoder
        nlayers = 2  # number of nn.TransformerEncoderLayer in nn.TransformerEncoder
        nhead = 2  # number of heads in nn.MultiheadAttention
        dropout = 0.2  # dropout probability
        self.n_classes = 4
        self.model = TransformerModel(n_features, emsize, nhead, d_hid, nlayers, dropout, self.n_classes).to(device)
        self.x_val = None
        self.y_val = None

    def set_validation_data(self, x_test, y_test):
        self.x_val = x_test
        self.y_val = y_test

    def get_polynomial_decay_schedule_with_warmup(
            self, optimizer, num_warmup_steps, num_training_steps, lr_end=1e-6, power=1.0, last_epoch=-1
    ):

        lr_init = optimizer.defaults["lr"]
        if not (lr_init > lr_end):
            raise ValueError(f"lr_end ({lr_end}) must be be smaller than initial lr ({lr_init})")

        def lr_lambda(current_step: int):
            if current_step < num_warmup_steps:
                return float(current_step) / float(max(1, num_warmup_steps))
            elif current_step > num_training_steps:
                return lr_end / lr_init  # as LambdaLR multiplies by lr_init
            else:
                lr_range = lr_init - lr_end
                decay_steps = num_training_steps - num_warmup_steps
                pct_remaining = 1 - (current_step - num_warmup_steps) / decay_steps
                decay = lr_range * pct_remaining ** power + lr_end
                return decay / lr_init  # as LambdaLR multiplies by lr_init

        return LambdaLR(optimizer, lr_lambda, last_epoch)

    def fit(self, X, y):
        best_f1 = float('inf')
        epochs = 300
        # criterion = nn.CrossEntropyLoss()
        samples_per_cls = [len(np.where(y == t)[0]) for t in np.unique(y)]
        no_of_classes = len(np.unique(y))

        focal_loss = Loss(
            loss_type="focal_loss",
            samples_per_class=samples_per_cls,
            class_balanced=True
        )

        criterion = focal_loss
        initial_lr = 1e-3  # learning rate
        optimizer = torch.optim.AdamW(self.model.parameters(), lr=initial_lr)
        scheduler = self.get_polynomial_decay_schedule_with_warmup(optimizer, 128, 128*300)  # torch.optim.lr_scheduler.StepLR(optimizer, 1, gamma=0.95)
        best_model = None

        try:
            for epoch in range(1, epochs + 1):
                epoch_start_time = time.time()
                train_epoch(self.model, X, y, criterion, optimizer, scheduler, epoch, self.n_classes)
                assert self.x_val is not None
                assert self.y_val is not None
                val_loss, acc, f1_micro, f1_macro = evaluate(self.model, (self.x_val, self.y_val), criterion,
                                                             self.n_classes)
                elapsed = time.time() - epoch_start_time
                print('-' * 89)
                print(f'| end of epoch {epoch:3d} | time: {elapsed:5.2f}s | '
                      f'valid loss {val_loss:5.2f}  | acc {acc:5.2f} | lr {scheduler.get_last_lr()[0]:02.6f} | '
                      f'f1_micro {f1_micro:5.2f} | f1_macro {f1_macro:5.2f}')
                print('-' * 89)

                if f1_micro < best_f1:
                    best_f1 = f1_micro
                    best_model = copy.deepcopy(self.model)

                scheduler.step()
        except KeyboardInterrupt:
            print("Finishing training...")
        self.model = best_model

    def predict(self, X):
        return self.model(X)


class PositionalEncoding(nn.Module):

    def __init__(self, d_model: int, dropout: float = 0.1, max_len: int = 200):
        super().__init__()
        self.dropout = nn.Dropout(p=dropout)

        position = torch.arange(max_len).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2) * (-math.log(10000.0) / d_model))
        pe = torch.zeros(max_len, 1, d_model)
        pe[:, 0, 0::2] = torch.sin(position * div_term)
        pe[:, 0, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)

    def forward(self, x: Tensor) -> Tensor:
        """
        Args:
            x: Tensor, shape [seq_len, batch_size, embedding_dim]
        """
        x = x + self.pe[:x.size(0)]
        return self.dropout(x)


class TransformerModel(nn.Module):

    def __init__(self, dim_input: int, d_model: int, nhead: int, d_hid: int,
                 nlayers: int, dropout: float = 0.5, n_classes=4):
        super().__init__()
        self.model_type = 'Transformer'
        self.pos_encoder = PositionalEncoding(d_model, dropout)
        encoder_layers = TransformerEncoderLayer(d_model, nhead, d_hid, dropout, batch_first=False)
        self.transformer_encoder = TransformerEncoder(encoder_layers, nlayers)
        self.encoder = nn.Linear(dim_input, d_model)
        self.d_model = d_model
        self.classifier = nn.Linear(d_model, n_classes)

        self.init_weights()

    def init_weights(self) -> None:
        initrange = 0.1
        self.encoder.weight.data.uniform_(-initrange, initrange)
        self.classifier.bias.data.zero_()
        self.classifier.weight.data.uniform_(-initrange, initrange)

    def forward(self, src: Tensor, src_mask: Tensor = None) -> Tensor:
        """
        Args:
            src: Tensor, shape [seq_len, batch_size]
            src_mask: Tensor, shape [seq_len, seq_len]

        Returns:
            output Tensor of shape [seq_len, batch_size, ntoken]
        """
        # exchange batch and seq dim
        src_key_padding_mask = src[:, :, 0].isnan()  # this mask is over elements of the sequence,
        # replace nans with 0s
        src = src.nan_to_num()
        # not over the sequence itself. Shape: [batch_size, seq_len]
        src = src.permute(1, 0, 2)
        src = self.encoder(src) * math.sqrt(self.d_model)
        src = self.pos_encoder(src)
        output = self.transformer_encoder(src, src_mask, src_key_padding_mask=src_key_padding_mask)
        output = self.classifier(output[0, :, :])
        output = F.log_softmax(output, dim=1)
        return output


if __name__ == '__main__':
    # load data
    # x_data = torch.load('tensor.pt').float()
    # torch.save(x_data,'tensor2.pt')
    if not os.path.exists('tensor_nomedian.pt'):
        print('Downloading data...', end='')
        file = requests.get(
            'https://nubeusc-my.sharepoint.com/:u:/g/personal/manuel_deprada_corral_usc_es/EZykiNRuuBFPsavgTJhAUrcBAAaIfu1RfeJEGkj1ZHnIOg?e=qib91G&download=1')
        print('Done. Loading data...', end='')
        x_data = torch.load(io.BytesIO(file.content))
        print('Done.')
    else:
        x_data = torch.load('tensor_nomedian.pt').float()
    # x_data = torch.load('tensor2.pt')
    y_train_file = "aWQseQowLDAKMSwwCjIsMAozLDEKNCwyCjUsMQo2LDAKNywxCjgsMgo5LDAKMTAsMgoxMSwwCjEyLDAKMTMsMAoxNCwyCjE1LDAKMTYsMQoxNywyCjE4LDIKMTksMAoyMCwyCjIxLDAKMjIsMgoyMywwCjI0LDAKMjUsMAoyNiwyCjI3LDAKMjgsMgoyOSwxCjMwLDMKMzEsMAozMiwwCjMzLDMKMzQsMAozNSwwCjM2LDIKMzcsMAozOCwyCjM5LDAKNDAsMgo0MSwwCjQyLDAKNDMsMAo0NCwyCjQ1LDAKNDYsMAo0NywyCjQ4LDIKNDksMgo1MCwwCjUxLDAKNTIsMAo1MywxCjU0LDIKNTUsMgo1NiwwCjU3LDAKNTgsMgo1OSwwCjYwLDIKNjEsMAo2MiwwCjYzLDIKNjQsMAo2NSwwCjY2LDIKNjcsMAo2OCwwCjY5LDIKNzAsMAo3MSwzCjcyLDAKNzMsMAo3NCwzCjc1LDIKNzYsMAo3NywxCjc4LDAKNzksMAo4MCwwCjgxLDAKODIsMgo4MywwCjg0LDAKODUsMAo4NiwwCjg3LDIKODgsMAo4OSwyCjkwLDIKOTEsMAo5MiwyCjkzLDAKOTQsMAo5NSwyCjk2LDEKOTcsMAo5OCwwCjk5LDAKMTAwLDIKMTAxLDAKMTAyLDMKMTAzLDMKMTA0LDIKMTA1LDIKMTA2LDAKMTA3LDAKMTA4LDEKMTA5LDIKMTEwLDAKMTExLDAKMTEyLDAKMTEzLDEKMTE0LDIKMTE1LDIKMTE2LDIKMTE3LDIKMTE4LDAKMTE5LDAKMTIwLDAKMTIxLDAKMTIyLDIKMTIzLDEKMTI0LDIKMTI1LDAKMTI2LDEKMTI3LDIKMTI4LDEKMTI5LDAKMTMwLDAKMTMxLDEKMTMyLDAKMTMzLDAKMTM0LDAKMTM1LDAKMTM2LDAKMTM3LDIKMTM4LDEKMTM5LDAKMTQwLDAKMTQxLDAKMTQyLDIKMTQzLDAKMTQ0LDEKMTQ1LDEKMTQ2LDIKMTQ3LDAKMTQ4LDIKMTQ5LDIKMTUwLDAKMTUxLDAKMTUyLDAKMTUzLDAKMTU0LDAKMTU1LDAKMTU2LDAKMTU3LDIKMTU4LDAKMTU5LDAKMTYwLDIKMTYxLDAKMTYyLDAKMTYzLDIKMTY0LDAKMTY1LDEKMTY2LDAKMTY3LDAKMTY4LDAKMTY5LDIKMTcwLDAKMTcxLDMKMTcyLDIKMTczLDAKMTc0LDAKMTc1LDIKMTc2LDAKMTc3LDAKMTc4LDAKMTc5LDIKMTgwLDAKMTgxLDAKMTgyLDIKMTgzLDIKMTg0LDAKMTg1LDIKMTg2LDIKMTg3LDEKMTg4LDEKMTg5LDAKMTkwLDIKMTkxLDAKMTkyLDAKMTkzLDAKMTk0LDAKMTk1LDIKMTk2LDAKMTk3LDMKMTk4LDAKMTk5LDEKMjAwLDIKMjAxLDMKMjAyLDAKMjAzLDIKMjA0LDAKMjA1LDAKMjA2LDAKMjA3LDEKMjA4LDAKMjA5LDAKMjEwLDAKMjExLDAKMjEyLDAKMjEzLDEKMjE0LDAKMjE1LDAKMjE2LDIKMjE3LDIKMjE4LDEKMjE5LDAKMjIwLDIKMjIxLDIKMjIyLDIKMjIzLDEKMjI0LDAKMjI1LDAKMjI2LDAKMjI3LDAKMjI4LDAKMjI5LDAKMjMwLDEKMjMxLDAKMjMyLDAKMjMzLDIKMjM0LDAKMjM1LDIKMjM2LDIKMjM3LDAKMjM4LDIKMjM5LDAKMjQwLDAKMjQxLDIKMjQyLDEKMjQzLDAKMjQ0LDIKMjQ1LDIKMjQ2LDAKMjQ3LDAKMjQ4LDAKMjQ5LDAKMjUwLDIKMjUxLDIKMjUyLDAKMjUzLDAKMjU0LDAKMjU1LDAKMjU2LDAKMjU3LDIKMjU4LDAKMjU5LDIKMjYwLDAKMjYxLDIKMjYyLDAKMjYzLDAKMjY0LDIKMjY1LDAKMjY2LDIKMjY3LDAKMjY4LDAKMjY5LDMKMjcwLDAKMjcxLDIKMjcyLDIKMjczLDIKMjc0LDIKMjc1LDIKMjc2LDAKMjc3LDAKMjc4LDAKMjc5LDAKMjgwLDAKMjgxLDAKMjgyLDAKMjgzLDIKMjg0LDAKMjg1LDAKMjg2LDAKMjg3LDAKMjg4LDAKMjg5LDAKMjkwLDIKMjkxLDMKMjkyLDIKMjkzLDAKMjk0LDAKMjk1LDIKMjk2LDIKMjk3LDAKMjk4LDIKMjk5LDAKMzAwLDAKMzAxLDAKMzAyLDAKMzAzLDAKMzA0LDIKMzA1LDAKMzA2LDEKMzA3LDEKMzA4LDAKMzA5LDAKMzEwLDIKMzExLDAKMzEyLDAKMzEzLDAKMzE0LDAKMzE1LDAKMzE2LDAKMzE3LDMKMzE4LDIKMzE5LDAKMzIwLDAKMzIxLDAKMzIyLDAKMzIzLDIKMzI0LDAKMzI1LDAKMzI2LDAKMzI3LDIKMzI4LDAKMzI5LDEKMzMwLDAKMzMxLDAKMzMyLDAKMzMzLDMKMzM0LDAKMzM1LDAKMzM2LDAKMzM3LDAKMzM4LDAKMzM5LDAKMzQwLDAKMzQxLDAKMzQyLDAKMzQzLDIKMzQ0LDAKMzQ1LDAKMzQ2LDAKMzQ3LDIKMzQ4LDIKMzQ5LDAKMzUwLDEKMzUxLDAKMzUyLDAKMzUzLDAKMzU0LDAKMzU1LDIKMzU2LDIKMzU3LDEKMzU4LDAKMzU5LDAKMzYwLDIKMzYxLDAKMzYyLDIKMzYzLDIKMzY0LDIKMzY1LDIKMzY2LDAKMzY3LDAKMzY4LDAKMzY5LDAKMzcwLDAKMzcxLDAKMzcyLDAKMzczLDIKMzc0LDAKMzc1LDIKMzc2LDAKMzc3LDAKMzc4LDIKMzc5LDAKMzgwLDAKMzgxLDAKMzgyLDEKMzgzLDEKMzg0LDAKMzg1LDAKMzg2LDAKMzg3LDAKMzg4LDAKMzg5LDAKMzkwLDAKMzkxLDAKMzkyLDIKMzkzLDIKMzk0LDAKMzk1LDAKMzk2LDIKMzk3LDAKMzk4LDAKMzk5LDAKNDAwLDAKNDAxLDAKNDAyLDAKNDAzLDAKNDA0LDAKNDA1LDEKNDA2LDIKNDA3LDIKNDA4LDIKNDA5LDAKNDEwLDIKNDExLDAKNDEyLDEKNDEzLDAKNDE0LDAKNDE1LDAKNDE2LDIKNDE3LDIKNDE4LDAKNDE5LDAKNDIwLDAKNDIxLDAKNDIyLDAKNDIzLDAKNDI0LDAKNDI1LDAKNDI2LDAKNDI3LDIKNDI4LDIKNDI5LDIKNDMwLDAKNDMxLDIKNDMyLDIKNDMzLDIKNDM0LDEKNDM1LDIKNDM2LDIKNDM3LDIKNDM4LDMKNDM5LDAKNDQwLDEKNDQxLDAKNDQyLDAKNDQzLDAKNDQ0LDAKNDQ1LDAKNDQ2LDIKNDQ3LDAKNDQ4LDMKNDQ5LDAKNDUwLDIKNDUxLDAKNDUyLDAKNDUzLDAKNDU0LDEKNDU1LDAKNDU2LDAKNDU3LDIKNDU4LDAKNDU5LDAKNDYwLDIKNDYxLDAKNDYyLDAKNDYzLDIKNDY0LDAKNDY1LDAKNDY2LDAKNDY3LDEKNDY4LDAKNDY5LDAKNDcwLDAKNDcxLDAKNDcyLDIKNDczLDIKNDc0LDAKNDc1LDIKNDc2LDEKNDc3LDAKNDc4LDIKNDc5LDIKNDgwLDAKNDgxLDIKNDgyLDEKNDgzLDAKNDg0LDAKNDg1LDIKNDg2LDAKNDg3LDIKNDg4LDAKNDg5LDAKNDkwLDAKNDkxLDAKNDkyLDAKNDkzLDAKNDk0LDAKNDk1LDEKNDk2LDIKNDk3LDEKNDk4LDIKNDk5LDAKNTAwLDAKNTAxLDMKNTAyLDAKNTAzLDIKNTA0LDAKNTA1LDAKNTA2LDAKNTA3LDAKNTA4LDIKNTA5LDAKNTEwLDAKNTExLDAKNTEyLDEKNTEzLDAKNTE0LDEKNTE1LDAKNTE2LDEKNTE3LDIKNTE4LDIKNTE5LDAKNTIwLDAKNTIxLDAKNTIyLDIKNTIzLDAKNTI0LDIKNTI1LDIKNTI2LDIKNTI3LDMKNTI4LDAKNTI5LDAKNTMwLDAKNTMxLDAKNTMyLDIKNTMzLDIKNTM0LDAKNTM1LDIKNTM2LDIKNTM3LDAKNTM4LDAKNTM5LDAKNTQwLDAKNTQxLDAKNTQyLDIKNTQzLDAKNTQ0LDAKNTQ1LDAKNTQ2LDAKNTQ3LDAKNTQ4LDEKNTQ5LDIKNTUwLDAKNTUxLDIKNTUyLDAKNTUzLDIKNTU0LDAKNTU1LDEKNTU2LDAKNTU3LDAKNTU4LDEKNTU5LDEKNTYwLDAKNTYxLDAKNTYyLDIKNTYzLDAKNTY0LDAKNTY1LDIKNTY2LDIKNTY3LDAKNTY4LDAKNTY5LDAKNTcwLDAKNTcxLDAKNTcyLDAKNTczLDAKNTc0LDAKNTc1LDAKNTc2LDAKNTc3LDIKNTc4LDAKNTc5LDIKNTgwLDAKNTgxLDAKNTgyLDIKNTgzLDAKNTg0LDEKNTg1LDAKNTg2LDAKNTg3LDIKNTg4LDIKNTg5LDAKNTkwLDEKNTkxLDEKNTkyLDAKNTkzLDIKNTk0LDAKNTk1LDIKNTk2LDAKNTk3LDAKNTk4LDIKNTk5LDAKNjAwLDAKNjAxLDAKNjAyLDEKNjAzLDAKNjA0LDAKNjA1LDAKNjA2LDAKNjA3LDAKNjA4LDAKNjA5LDAKNjEwLDAKNjExLDEKNjEyLDIKNjEzLDIKNjE0LDAKNjE1LDAKNjE2LDAKNjE3LDIKNjE4LDIKNjE5LDAKNjIwLDAKNjIxLDAKNjIyLDIKNjIzLDAKNjI0LDAKNjI1LDIKNjI2LDAKNjI3LDAKNjI4LDIKNjI5LDAKNjMwLDAKNjMxLDAKNjMyLDEKNjMzLDAKNjM0LDEKNjM1LDAKNjM2LDAKNjM3LDAKNjM4LDAKNjM5LDAKNjQwLDAKNjQxLDIKNjQyLDIKNjQzLDAKNjQ0LDIKNjQ1LDAKNjQ2LDAKNjQ3LDIKNjQ4LDAKNjQ5LDAKNjUwLDIKNjUxLDAKNjUyLDAKNjUzLDAKNjU0LDEKNjU1LDIKNjU2LDEKNjU3LDAKNjU4LDAKNjU5LDIKNjYwLDIKNjYxLDAKNjYyLDAKNjYzLDIKNjY0LDMKNjY1LDAKNjY2LDEKNjY3LDIKNjY4LDAKNjY5LDIKNjcwLDIKNjcxLDIKNjcyLDIKNjczLDAKNjc0LDAKNjc1LDIKNjc2LDAKNjc3LDAKNjc4LDAKNjc5LDAKNjgwLDAKNjgxLDAKNjgyLDEKNjgzLDAKNjg0LDEKNjg1LDAKNjg2LDAKNjg3LDAKNjg4LDAKNjg5LDIKNjkwLDMKNjkxLDAKNjkyLDIKNjkzLDAKNjk0LDEKNjk1LDAKNjk2LDIKNjk3LDAKNjk4LDIKNjk5LDIKNzAwLDIKNzAxLDAKNzAyLDAKNzAzLDIKNzA0LDAKNzA1LDEKNzA2LDAKNzA3LDIKNzA4LDAKNzA5LDAKNzEwLDAKNzExLDAKNzEyLDAKNzEzLDAKNzE0LDIKNzE1LDIKNzE2LDAKNzE3LDEKNzE4LDAKNzE5LDAKNzIwLDAKNzIxLDAKNzIyLDIKNzIzLDIKNzI0LDIKNzI1LDAKNzI2LDAKNzI3LDAKNzI4LDIKNzI5LDAKNzMwLDAKNzMxLDAKNzMyLDAKNzMzLDEKNzM0LDAKNzM1LDEKNzM2LDAKNzM3LDIKNzM4LDAKNzM5LDAKNzQwLDIKNzQxLDEKNzQyLDAKNzQzLDAKNzQ0LDEKNzQ1LDAKNzQ2LDAKNzQ3LDAKNzQ4LDAKNzQ5LDAKNzUwLDAKNzUxLDAKNzUyLDEKNzUzLDAKNzU0LDAKNzU1LDAKNzU2LDAKNzU3LDAKNzU4LDAKNzU5LDIKNzYwLDIKNzYxLDAKNzYyLDIKNzYzLDMKNzY0LDAKNzY1LDIKNzY2LDAKNzY3LDIKNzY4LDIKNzY5LDAKNzcwLDMKNzcxLDAKNzcyLDAKNzczLDIKNzc0LDAKNzc1LDIKNzc2LDMKNzc3LDIKNzc4LDAKNzc5LDEKNzgwLDAKNzgxLDAKNzgyLDIKNzgzLDAKNzg0LDIKNzg1LDAKNzg2LDAKNzg3LDEKNzg4LDIKNzg5LDIKNzkwLDEKNzkxLDAKNzkyLDIKNzkzLDAKNzk0LDAKNzk1LDAKNzk2LDEKNzk3LDIKNzk4LDAKNzk5LDAKODAwLDAKODAxLDAKODAyLDEKODAzLDIKODA0LDAKODA1LDAKODA2LDAKODA3LDAKODA4LDAKODA5LDEKODEwLDAKODExLDAKODEyLDIKODEzLDAKODE0LDEKODE1LDMKODE2LDEKODE3LDAKODE4LDMKODE5LDAKODIwLDAKODIxLDAKODIyLDAKODIzLDIKODI0LDAKODI1LDIKODI2LDAKODI3LDEKODI4LDIKODI5LDAKODMwLDAKODMxLDAKODMyLDAKODMzLDAKODM0LDIKODM1LDMKODM2LDIKODM3LDIKODM4LDIKODM5LDIKODQwLDIKODQxLDAKODQyLDAKODQzLDAKODQ0LDAKODQ1LDAKODQ2LDMKODQ3LDAKODQ4LDIKODQ5LDAKODUwLDIKODUxLDAKODUyLDAKODUzLDAKODU0LDAKODU1LDAKODU2LDAKODU3LDAKODU4LDAKODU5LDIKODYwLDIKODYxLDIKODYyLDEKODYzLDIKODY0LDAKODY1LDAKODY2LDEKODY3LDAKODY4LDAKODY5LDAKODcwLDMKODcxLDAKODcyLDAKODczLDIKODc0LDIKODc1LDIKODc2LDIKODc3LDAKODc4LDIKODc5LDAKODgwLDAKODgxLDAKODgyLDAKODgzLDAKODg0LDIKODg1LDIKODg2LDEKODg3LDMKODg4LDIKODg5LDAKODkwLDIKODkxLDAKODkyLDAKODkzLDIKODk0LDAKODk1LDEKODk2LDAKODk3LDAKODk4LDAKODk5LDAKOTAwLDIKOTAxLDIKOTAyLDIKOTAzLDAKOTA0LDIKOTA1LDEKOTA2LDAKOTA3LDIKOTA4LDAKOTA5LDAKOTEwLDAKOTExLDIKOTEyLDAKOTEzLDAKOTE0LDEKOTE1LDIKOTE2LDAKOTE3LDAKOTE4LDAKOTE5LDAKOTIwLDEKOTIxLDAKOTIyLDAKOTIzLDAKOTI0LDAKOTI1LDEKOTI2LDEKOTI3LDAKOTI4LDAKOTI5LDMKOTMwLDIKOTMxLDEKOTMyLDIKOTMzLDAKOTM0LDAKOTM1LDIKOTM2LDAKOTM3LDEKOTM4LDAKOTM5LDAKOTQwLDIKOTQxLDAKOTQyLDAKOTQzLDIKOTQ0LDIKOTQ1LDAKOTQ2LDAKOTQ3LDAKOTQ4LDAKOTQ5LDAKOTUwLDAKOTUxLDAKOTUyLDAKOTUzLDIKOTU0LDIKOTU1LDAKOTU2LDEKOTU3LDAKOTU4LDAKOTU5LDIKOTYwLDAKOTYxLDIKOTYyLDAKOTYzLDAKOTY0LDAKOTY1LDAKOTY2LDAKOTY3LDIKOTY4LDMKOTY5LDIKOTcwLDIKOTcxLDIKOTcyLDAKOTczLDAKOTc0LDIKOTc1LDAKOTc2LDAKOTc3LDAKOTc4LDIKOTc5LDAKOTgwLDIKOTgxLDAKOTgyLDAKOTgzLDAKOTg0LDAKOTg1LDIKOTg2LDIKOTg3LDIKOTg4LDAKOTg5LDAKOTkwLDAKOTkxLDIKOTkyLDIKOTkzLDAKOTk0LDAKOTk1LDAKOTk2LDAKOTk3LDAKOTk4LDAKOTk5LDIKMTAwMCwyCjEwMDEsMAoxMDAyLDMKMTAwMywwCjEwMDQsMAoxMDA1LDAKMTAwNiwyCjEwMDcsMgoxMDA4LDAKMTAwOSwwCjEwMTAsMAoxMDExLDIKMTAxMiwwCjEwMTMsMgoxMDE0LDIKMTAxNSwyCjEwMTYsMgoxMDE3LDAKMTAxOCwwCjEwMTksMAoxMDIwLDEKMTAyMSwwCjEwMjIsMwoxMDIzLDAKMTAyNCwyCjEwMjUsMAoxMDI2LDAKMTAyNywyCjEwMjgsMAoxMDI5LDIKMTAzMCwyCjEwMzEsMAoxMDMyLDAKMTAzMywwCjEwMzQsMgoxMDM1LDAKMTAzNiwyCjEwMzcsMAoxMDM4LDIKMTAzOSwyCjEwNDAsMgoxMDQxLDEKMTA0MiwyCjEwNDMsMQoxMDQ0LDMKMTA0NSwyCjEwNDYsMAoxMDQ3LDAKMTA0OCwwCjEwNDksMAoxMDUwLDAKMTA1MSwxCjEwNTIsMAoxMDUzLDAKMTA1NCwwCjEwNTUsMgoxMDU2LDEKMTA1NywyCjEwNTgsMAoxMDU5LDMKMTA2MCwwCjEwNjEsMgoxMDYyLDIKMTA2MywyCjEwNjQsMAoxMDY1LDAKMTA2NiwwCjEwNjcsMwoxMDY4LDAKMTA2OSwwCjEwNzAsMgoxMDcxLDAKMTA3MiwwCjEwNzMsMAoxMDc0LDEKMTA3NSwzCjEwNzYsMAoxMDc3LDAKMTA3OCwxCjEwNzksMAoxMDgwLDAKMTA4MSwwCjEwODIsMAoxMDgzLDEKMTA4NCwwCjEwODUsMQoxMDg2LDIKMTA4NywwCjEwODgsMAoxMDg5LDIKMTA5MCwwCjEwOTEsMAoxMDkyLDIKMTA5MywwCjEwOTQsMAoxMDk1LDIKMTA5NiwyCjEwOTcsMAoxMDk4LDAKMTA5OSwwCjExMDAsMgoxMTAxLDEKMTEwMiwwCjExMDMsMgoxMTA0LDAKMTEwNSwyCjExMDYsMAoxMTA3LDAKMTEwOCwyCjExMDksMQoxMTEwLDEKMTExMSwwCjExMTIsMAoxMTEzLDAKMTExNCwwCjExMTUsMwoxMTE2LDAKMTExNywwCjExMTgsMgoxMTE5LDAKMTEyMCwwCjExMjEsMAoxMTIyLDAKMTEyMywyCjExMjQsMAoxMTI1LDIKMTEyNiwwCjExMjcsMAoxMTI4LDAKMTEyOSwwCjExMzAsMwoxMTMxLDIKMTEzMiwyCjExMzMsMAoxMTM0LDAKMTEzNSwyCjExMzYsMAoxMTM3LDIKMTEzOCwyCjExMzksMQoxMTQwLDAKMTE0MSwwCjExNDIsMgoxMTQzLDIKMTE0NCwwCjExNDUsMgoxMTQ2LDIKMTE0NywzCjExNDgsMAoxMTQ5LDAKMTE1MCwyCjExNTEsMgoxMTUyLDAKMTE1MywwCjExNTQsMAoxMTU1LDAKMTE1NiwwCjExNTcsMAoxMTU4LDAKMTE1OSwwCjExNjAsMAoxMTYxLDAKMTE2MiwwCjExNjMsMAoxMTY0LDAKMTE2NSwyCjExNjYsMQoxMTY3LDEKMTE2OCwwCjExNjksMAoxMTcwLDIKMTE3MSwwCjExNzIsMAoxMTczLDAKMTE3NCwxCjExNzUsMgoxMTc2LDAKMTE3NywwCjExNzgsMAoxMTc5LDIKMTE4MCwwCjExODEsMQoxMTgyLDIKMTE4MywwCjExODQsMAoxMTg1LDAKMTE4NiwwCjExODcsMgoxMTg4LDIKMTE4OSwxCjExOTAsMgoxMTkxLDIKMTE5MiwyCjExOTMsMAoxMTk0LDAKMTE5NSwwCjExOTYsMAoxMTk3LDAKMTE5OCwyCjExOTksMgoxMjAwLDAKMTIwMSwwCjEyMDIsMgoxMjAzLDAKMTIwNCwwCjEyMDUsMAoxMjA2LDAKMTIwNywwCjEyMDgsMAoxMjA5LDAKMTIxMCwyCjEyMTEsMgoxMjEyLDAKMTIxMywwCjEyMTQsMAoxMjE1LDIKMTIxNiwyCjEyMTcsMgoxMjE4LDAKMTIxOSwwCjEyMjAsMAoxMjIxLDIKMTIyMiwwCjEyMjMsMgoxMjI0LDAKMTIyNSwwCjEyMjYsMQoxMjI3LDAKMTIyOCwwCjEyMjksMgoxMjMwLDIKMTIzMSwxCjEyMzIsMAoxMjMzLDIKMTIzNCwwCjEyMzUsMAoxMjM2LDAKMTIzNywwCjEyMzgsMAoxMjM5LDIKMTI0MCwwCjEyNDEsMAoxMjQyLDAKMTI0MywwCjEyNDQsMAoxMjQ1LDMKMTI0NiwyCjEyNDcsMgoxMjQ4LDAKMTI0OSwwCjEyNTAsMQoxMjUxLDAKMTI1MiwwCjEyNTMsMgoxMjU0LDAKMTI1NSwwCjEyNTYsMQoxMjU3LDAKMTI1OCwzCjEyNTksMgoxMjYwLDAKMTI2MSwwCjEyNjIsMAoxMjYzLDAKMTI2NCwwCjEyNjUsMAoxMjY2LDAKMTI2NywwCjEyNjgsMAoxMjY5LDIKMTI3MCwyCjEyNzEsMAoxMjcyLDAKMTI3MywyCjEyNzQsMAoxMjc1LDAKMTI3NiwyCjEyNzcsMgoxMjc4LDIKMTI3OSwwCjEyODAsMAoxMjgxLDAKMTI4MiwwCjEyODMsMAoxMjg0LDAKMTI4NSwwCjEyODYsMAoxMjg3LDAKMTI4OCwwCjEyODksMAoxMjkwLDMKMTI5MSwyCjEyOTIsMAoxMjkzLDMKMTI5NCwwCjEyOTUsMAoxMjk2LDIKMTI5NywwCjEyOTgsMAoxMjk5LDAKMTMwMCwwCjEzMDEsMgoxMzAyLDAKMTMwMywwCjEzMDQsMQoxMzA1LDAKMTMwNiwyCjEzMDcsMAoxMzA4LDIKMTMwOSwyCjEzMTAsMAoxMzExLDAKMTMxMiwyCjEzMTMsMAoxMzE0LDAKMTMxNSwyCjEzMTYsMgoxMzE3LDIKMTMxOCwyCjEzMTksMAoxMzIwLDAKMTMyMSwwCjEzMjIsMQoxMzIzLDIKMTMyNCwwCjEzMjUsMAoxMzI2LDIKMTMyNywwCjEzMjgsMgoxMzI5LDEKMTMzMCwzCjEzMzEsMAoxMzMyLDIKMTMzMywwCjEzMzQsMgoxMzM1LDAKMTMzNiwyCjEzMzcsMAoxMzM4LDAKMTMzOSwyCjEzNDAsMAoxMzQxLDAKMTM0MiwxCjEzNDMsMAoxMzQ0LDAKMTM0NSwzCjEzNDYsMAoxMzQ3LDEKMTM0OCwwCjEzNDksMAoxMzUwLDEKMTM1MSwwCjEzNTIsMgoxMzUzLDAKMTM1NCwyCjEzNTUsMQoxMzU2LDAKMTM1NywwCjEzNTgsMAoxMzU5LDIKMTM2MCwxCjEzNjEsMgoxMzYyLDIKMTM2MywwCjEzNjQsMAoxMzY1LDIKMTM2NiwyCjEzNjcsMAoxMzY4LDIKMTM2OSwxCjEzNzAsMAoxMzcxLDAKMTM3MiwwCjEzNzMsMAoxMzc0LDIKMTM3NSwyCjEzNzYsMQoxMzc3LDAKMTM3OCwwCjEzNzksMAoxMzgwLDMKMTM4MSwwCjEzODIsMgoxMzgzLDIKMTM4NCwyCjEzODUsMAoxMzg2LDEKMTM4NywwCjEzODgsMgoxMzg5LDEKMTM5MCwwCjEzOTEsMQoxMzkyLDIKMTM5MywyCjEzOTQsMAoxMzk1LDAKMTM5NiwwCjEzOTcsMAoxMzk4LDIKMTM5OSwwCjE0MDAsMAoxNDAxLDAKMTQwMiwwCjE0MDMsMAoxNDA0LDAKMTQwNSwwCjE0MDYsMAoxNDA3LDEKMTQwOCwyCjE0MDksMAoxNDEwLDAKMTQxMSwwCjE0MTIsMgoxNDEzLDIKMTQxNCwyCjE0MTUsMgoxNDE2LDIKMTQxNywwCjE0MTgsMAoxNDE5LDIKMTQyMCwwCjE0MjEsMAoxNDIyLDAKMTQyMywwCjE0MjQsMgoxNDI1LDAKMTQyNiwwCjE0MjcsMgoxNDI4LDAKMTQyOSwwCjE0MzAsMgoxNDMxLDAKMTQzMiwyCjE0MzMsMgoxNDM0LDIKMTQzNSwyCjE0MzYsMAoxNDM3LDAKMTQzOCwwCjE0MzksMAoxNDQwLDIKMTQ0MSwwCjE0NDIsMAoxNDQzLDAKMTQ0NCwwCjE0NDUsMgoxNDQ2LDIKMTQ0NywwCjE0NDgsMgoxNDQ5LDAKMTQ1MCwyCjE0NTEsMAoxNDUyLDAKMTQ1MywwCjE0NTQsMAoxNDU1LDAKMTQ1NiwyCjE0NTcsMAoxNDU4LDAKMTQ1OSwwCjE0NjAsMAoxNDYxLDIKMTQ2MiwxCjE0NjMsMAoxNDY0LDAKMTQ2NSwwCjE0NjYsMgoxNDY3LDIKMTQ2OCwyCjE0NjksMAoxNDcwLDIKMTQ3MSwwCjE0NzIsMgoxNDczLDIKMTQ3NCwyCjE0NzUsMgoxNDc2LDAKMTQ3NywwCjE0NzgsMAoxNDc5LDAKMTQ4MCwwCjE0ODEsMgoxNDgyLDAKMTQ4MywwCjE0ODQsMAoxNDg1LDAKMTQ4NiwwCjE0ODcsMAoxNDg4LDAKMTQ4OSwxCjE0OTAsMQoxNDkxLDAKMTQ5MiwyCjE0OTMsMAoxNDk0LDAKMTQ5NSwyCjE0OTYsMwoxNDk3LDIKMTQ5OCwwCjE0OTksMAoxNTAwLDAKMTUwMSwxCjE1MDIsMgoxNTAzLDAKMTUwNCwwCjE1MDUsMQoxNTA2LDIKMTUwNywwCjE1MDgsMgoxNTA5LDIKMTUxMCwwCjE1MTEsMAoxNTEyLDAKMTUxMywxCjE1MTQsMAoxNTE1LDAKMTUxNiwxCjE1MTcsMgoxNTE4LDAKMTUxOSwxCjE1MjAsMAoxNTIxLDIKMTUyMiwyCjE1MjMsMgoxNTI0LDAKMTUyNSwyCjE1MjYsMAoxNTI3LDAKMTUyOCwzCjE1MjksMAoxNTMwLDIKMTUzMSwwCjE1MzIsMwoxNTMzLDAKMTUzNCwwCjE1MzUsMgoxNTM2LDIKMTUzNywwCjE1MzgsMQoxNTM5LDEKMTU0MCwyCjE1NDEsMAoxNTQyLDAKMTU0MywyCjE1NDQsMgoxNTQ1LDIKMTU0NiwwCjE1NDcsMgoxNTQ4LDAKMTU0OSwwCjE1NTAsMAoxNTUxLDAKMTU1MiwyCjE1NTMsMgoxNTU0LDMKMTU1NSwwCjE1NTYsMAoxNTU3LDAKMTU1OCwyCjE1NTksMAoxNTYwLDEKMTU2MSwwCjE1NjIsMAoxNTYzLDAKMTU2NCwwCjE1NjUsMgoxNTY2LDIKMTU2NywyCjE1NjgsMAoxNTY5LDAKMTU3MCwwCjE1NzEsMAoxNTcyLDAKMTU3MywwCjE1NzQsMAoxNTc1LDAKMTU3NiwwCjE1NzcsMgoxNTc4LDAKMTU3OSwzCjE1ODAsMgoxNTgxLDAKMTU4MiwyCjE1ODMsMAoxNTg0LDEKMTU4NSwwCjE1ODYsMAoxNTg3LDAKMTU4OCwwCjE1ODksMAoxNTkwLDAKMTU5MSwyCjE1OTIsMAoxNTkzLDAKMTU5NCwwCjE1OTUsMQoxNTk2LDAKMTU5NywwCjE1OTgsMgoxNTk5LDAKMTYwMCwzCjE2MDEsMAoxNjAyLDAKMTYwMywyCjE2MDQsMAoxNjA1LDAKMTYwNiwxCjE2MDcsMQoxNjA4LDAKMTYwOSwzCjE2MTAsMAoxNjExLDAKMTYxMiwwCjE2MTMsMAoxNjE0LDAKMTYxNSwwCjE2MTYsMgoxNjE3LDIKMTYxOCwwCjE2MTksMgoxNjIwLDAKMTYyMSwwCjE2MjIsMAoxNjIzLDEKMTYyNCwwCjE2MjUsMAoxNjI2LDIKMTYyNywxCjE2MjgsMQoxNjI5LDAKMTYzMCwyCjE2MzEsMQoxNjMyLDAKMTYzMywwCjE2MzQsMgoxNjM1LDAKMTYzNiwwCjE2MzcsMgoxNjM4LDAKMTYzOSwwCjE2NDAsMwoxNjQxLDAKMTY0MiwwCjE2NDMsMAoxNjQ0LDAKMTY0NSwwCjE2NDYsMAoxNjQ3LDAKMTY0OCwwCjE2NDksMgoxNjUwLDAKMTY1MSwyCjE2NTIsMAoxNjUzLDAKMTY1NCwxCjE2NTUsMAoxNjU2LDIKMTY1NywwCjE2NTgsMAoxNjU5LDIKMTY2MCwxCjE2NjEsMAoxNjYyLDAKMTY2MywwCjE2NjQsMgoxNjY1LDAKMTY2NiwyCjE2NjcsMgoxNjY4LDIKMTY2OSwyCjE2NzAsMAoxNjcxLDAKMTY3MiwyCjE2NzMsMAoxNjc0LDAKMTY3NSwwCjE2NzYsMAoxNjc3LDAKMTY3OCwwCjE2NzksMAoxNjgwLDAKMTY4MSwxCjE2ODIsMwoxNjgzLDAKMTY4NCwwCjE2ODUsMgoxNjg2LDAKMTY4NywwCjE2ODgsMAoxNjg5LDAKMTY5MCwwCjE2OTEsMAoxNjkyLDAKMTY5MywxCjE2OTQsMAoxNjk1LDAKMTY5NiwwCjE2OTcsMgoxNjk4LDIKMTY5OSwwCjE3MDAsMwoxNzAxLDAKMTcwMiwwCjE3MDMsMAoxNzA0LDIKMTcwNSwxCjE3MDYsMgoxNzA3LDEKMTcwOCwwCjE3MDksMAoxNzEwLDAKMTcxMSwwCjE3MTIsMAoxNzEzLDIKMTcxNCwwCjE3MTUsMgoxNzE2LDAKMTcxNywwCjE3MTgsMAoxNzE5LDAKMTcyMCwyCjE3MjEsMAoxNzIyLDAKMTcyMywyCjE3MjQsMAoxNzI1LDIKMTcyNiwwCjE3MjcsMAoxNzI4LDAKMTcyOSwyCjE3MzAsMAoxNzMxLDAKMTczMiwwCjE3MzMsMAoxNzM0LDIKMTczNSwyCjE3MzYsMAoxNzM3LDIKMTczOCwwCjE3MzksMAoxNzQwLDIKMTc0MSwyCjE3NDIsMAoxNzQzLDAKMTc0NCwwCjE3NDUsMAoxNzQ2LDAKMTc0NywwCjE3NDgsMAoxNzQ5LDAKMTc1MCwwCjE3NTEsMgoxNzUyLDAKMTc1MywwCjE3NTQsMgoxNzU1LDAKMTc1NiwyCjE3NTcsMAoxNzU4LDAKMTc1OSwwCjE3NjAsMAoxNzYxLDAKMTc2MiwwCjE3NjMsMgoxNzY0LDAKMTc2NSwwCjE3NjYsMAoxNzY3LDEKMTc2OCwwCjE3NjksMAoxNzcwLDAKMTc3MSwwCjE3NzIsMwoxNzczLDIKMTc3NCwwCjE3NzUsMQoxNzc2LDMKMTc3NywyCjE3NzgsMgoxNzc5LDAKMTc4MCwwCjE3ODEsMgoxNzgyLDAKMTc4MywyCjE3ODQsMAoxNzg1LDAKMTc4NiwwCjE3ODcsMgoxNzg4LDAKMTc4OSwyCjE3OTAsMAoxNzkxLDIKMTc5MiwyCjE3OTMsMgoxNzk0LDIKMTc5NSwyCjE3OTYsMAoxNzk3LDAKMTc5OCwwCjE3OTksMAoxODAwLDAKMTgwMSwwCjE4MDIsMwoxODAzLDAKMTgwNCwyCjE4MDUsMgoxODA2LDAKMTgwNywwCjE4MDgsMgoxODA5LDEKMTgxMCwwCjE4MTEsMgoxODEyLDAKMTgxMywxCjE4MTQsMAoxODE1LDIKMTgxNiwyCjE4MTcsMAoxODE4LDEKMTgxOSwyCjE4MjAsMAoxODIxLDIKMTgyMiwyCjE4MjMsMQoxODI0LDAKMTgyNSwwCjE4MjYsMgoxODI3LDAKMTgyOCwwCjE4MjksMwoxODMwLDAKMTgzMSwwCjE4MzIsMwoxODMzLDEKMTgzNCwyCjE4MzUsMAoxODM2LDEKMTgzNywyCjE4MzgsMAoxODM5LDIKMTg0MCwwCjE4NDEsMAoxODQyLDAKMTg0MywwCjE4NDQsMwoxODQ1LDIKMTg0NiwwCjE4NDcsMQoxODQ4LDAKMTg0OSwwCjE4NTAsMAoxODUxLDIKMTg1MiwwCjE4NTMsMgoxODU0LDAKMTg1NSwwCjE4NTYsMgoxODU3LDIKMTg1OCwwCjE4NTksMAoxODYwLDAKMTg2MSwwCjE4NjIsMAoxODYzLDAKMTg2NCwwCjE4NjUsMAoxODY2LDAKMTg2NywyCjE4NjgsMgoxODY5LDIKMTg3MCwyCjE4NzEsMAoxODcyLDAKMTg3MywwCjE4NzQsMgoxODc1LDAKMTg3NiwwCjE4NzcsMAoxODc4LDIKMTg3OSwyCjE4ODAsMgoxODgxLDIKMTg4MiwwCjE4ODMsMQoxODg0LDEKMTg4NSwwCjE4ODYsMgoxODg3LDAKMTg4OCwwCjE4ODksMAoxODkwLDIKMTg5MSwxCjE4OTIsMgoxODkzLDAKMTg5NCwwCjE4OTUsMAoxODk2LDAKMTg5NywwCjE4OTgsMgoxODk5LDAKMTkwMCwyCjE5MDEsMAoxOTAyLDAKMTkwMywxCjE5MDQsMAoxOTA1LDAKMTkwNiwwCjE5MDcsMAoxOTA4LDIKMTkwOSwwCjE5MTAsMAoxOTExLDMKMTkxMiwwCjE5MTMsMgoxOTE0LDAKMTkxNSwwCjE5MTYsMAoxOTE3LDMKMTkxOCwwCjE5MTksMgoxOTIwLDIKMTkyMSwwCjE5MjIsMgoxOTIzLDIKMTkyNCwyCjE5MjUsMwoxOTI2LDAKMTkyNywyCjE5MjgsMAoxOTI5LDAKMTkzMCwwCjE5MzEsMAoxOTMyLDAKMTkzMywwCjE5MzQsMAoxOTM1LDAKMTkzNiwxCjE5MzcsMAoxOTM4LDAKMTkzOSwwCjE5NDAsMAoxOTQxLDAKMTk0MiwwCjE5NDMsMAoxOTQ0LDAKMTk0NSwyCjE5NDYsMgoxOTQ3LDAKMTk0OCwyCjE5NDksMAoxOTUwLDAKMTk1MSwwCjE5NTIsMAoxOTUzLDAKMTk1NCwwCjE5NTUsMAoxOTU2LDIKMTk1NywwCjE5NTgsMgoxOTU5LDAKMTk2MCwwCjE5NjEsMQoxOTYyLDAKMTk2MywyCjE5NjQsMgoxOTY1LDAKMTk2NiwyCjE5NjcsMgoxOTY4LDIKMTk2OSwwCjE5NzAsMAoxOTcxLDIKMTk3MiwwCjE5NzMsMAoxOTc0LDAKMTk3NSwwCjE5NzYsMgoxOTc3LDMKMTk3OCwwCjE5NzksMAoxOTgwLDAKMTk4MSwxCjE5ODIsMQoxOTgzLDAKMTk4NCwwCjE5ODUsMAoxOTg2LDIKMTk4NywzCjE5ODgsMQoxOTg5LDIKMTk5MCwwCjE5OTEsMQoxOTkyLDAKMTk5MywwCjE5OTQsMQoxOTk1LDAKMTk5NiwwCjE5OTcsMAoxOTk4LDMKMTk5OSwwCjIwMDAsMAoyMDAxLDIKMjAwMiwwCjIwMDMsMgoyMDA0LDAKMjAwNSwwCjIwMDYsMAoyMDA3LDAKMjAwOCwyCjIwMDksMAoyMDEwLDAKMjAxMSwwCjIwMTIsMAoyMDEzLDIKMjAxNCwwCjIwMTUsMgoyMDE2LDMKMjAxNywyCjIwMTgsMgoyMDE5LDIKMjAyMCwwCjIwMjEsMAoyMDIyLDEKMjAyMywwCjIwMjQsMAoyMDI1LDAKMjAyNiwyCjIwMjcsMgoyMDI4LDAKMjAyOSwwCjIwMzAsMgoyMDMxLDAKMjAzMiwxCjIwMzMsMAoyMDM0LDAKMjAzNSwyCjIwMzYsMAoyMDM3LDAKMjAzOCwwCjIwMzksMgoyMDQwLDIKMjA0MSwxCjIwNDIsMgoyMDQzLDAKMjA0NCwwCjIwNDUsMgoyMDQ2LDIKMjA0NywwCjIwNDgsMAoyMDQ5LDAKMjA1MCwwCjIwNTEsMAoyMDUyLDAKMjA1MywyCjIwNTQsMgoyMDU1LDAKMjA1NiwwCjIwNTcsMAoyMDU4LDIKMjA1OSwyCjIwNjAsMQoyMDYxLDAKMjA2MiwwCjIwNjMsMAoyMDY0LDIKMjA2NSwwCjIwNjYsMgoyMDY3LDAKMjA2OCwwCjIwNjksMAoyMDcwLDAKMjA3MSwwCjIwNzIsMQoyMDczLDAKMjA3NCwwCjIwNzUsMgoyMDc2LDAKMjA3NywwCjIwNzgsMgoyMDc5LDAKMjA4MCwwCjIwODEsMQoyMDgyLDIKMjA4MywyCjIwODQsMAoyMDg1LDIKMjA4NiwwCjIwODcsMAoyMDg4LDAKMjA4OSwyCjIwOTAsMgoyMDkxLDAKMjA5MiwwCjIwOTMsMAoyMDk0LDIKMjA5NSwwCjIwOTYsMAoyMDk3LDAKMjA5OCwwCjIwOTksMAoyMTAwLDIKMjEwMSwyCjIxMDIsMgoyMTAzLDAKMjEwNCwwCjIxMDUsMAoyMTA2LDAKMjEwNywxCjIxMDgsMAoyMTA5LDAKMjExMCwyCjIxMTEsMAoyMTEyLDAKMjExMywwCjIxMTQsMgoyMTE1LDMKMjExNiwwCjIxMTcsMgoyMTE4LDAKMjExOSwwCjIxMjAsMAoyMTIxLDAKMjEyMiwwCjIxMjMsMAoyMTI0LDIKMjEyNSwwCjIxMjYsMAoyMTI3LDAKMjEyOCwwCjIxMjksMAoyMTMwLDAKMjEzMSwzCjIxMzIsMAoyMTMzLDAKMjEzNCwwCjIxMzUsMwoyMTM2LDAKMjEzNywwCjIxMzgsMgoyMTM5LDAKMjE0MCwyCjIxNDEsMAoyMTQyLDIKMjE0MywwCjIxNDQsMwoyMTQ1LDAKMjE0NiwwCjIxNDcsMgoyMTQ4LDAKMjE0OSwxCjIxNTAsMAoyMTUxLDAKMjE1MiwyCjIxNTMsMgoyMTU0LDAKMjE1NSwwCjIxNTYsMAoyMTU3LDEKMjE1OCwyCjIxNTksMAoyMTYwLDIKMjE2MSwwCjIxNjIsMgoyMTYzLDAKMjE2NCwwCjIxNjUsMQoyMTY2LDIKMjE2NywyCjIxNjgsMAoyMTY5LDAKMjE3MCwwCjIxNzEsMgoyMTcyLDAKMjE3MywyCjIxNzQsMgoyMTc1LDIKMjE3NiwwCjIxNzcsMAoyMTc4LDIKMjE3OSwwCjIxODAsMgoyMTgxLDAKMjE4MiwwCjIxODMsMAoyMTg0LDAKMjE4NSwxCjIxODYsMgoyMTg3LDAKMjE4OCwxCjIxODksMAoyMTkwLDAKMjE5MSwwCjIxOTIsMAoyMTkzLDAKMjE5NCwyCjIxOTUsMgoyMTk2LDAKMjE5NywyCjIxOTgsMAoyMTk5LDAKMjIwMCwxCjIyMDEsMgoyMjAyLDIKMjIwMywwCjIyMDQsMgoyMjA1LDAKMjIwNiwwCjIyMDcsMAoyMjA4LDAKMjIwOSwwCjIyMTAsMgoyMjExLDMKMjIxMiwwCjIyMTMsMQoyMjE0LDAKMjIxNSwyCjIyMTYsMAoyMjE3LDEKMjIxOCwwCjIyMTksMAoyMjIwLDAKMjIyMSwwCjIyMjIsMQoyMjIzLDAKMjIyNCwwCjIyMjUsMgoyMjI2LDIKMjIyNywxCjIyMjgsMAoyMjI5LDIKMjIzMCwyCjIyMzEsMAoyMjMyLDAKMjIzMywwCjIyMzQsMAoyMjM1LDIKMjIzNiwxCjIyMzcsMAoyMjM4LDAKMjIzOSwwCjIyNDAsMgoyMjQxLDAKMjI0MiwyCjIyNDMsMgoyMjQ0LDAKMjI0NSwwCjIyNDYsMAoyMjQ3LDAKMjI0OCwwCjIyNDksMAoyMjUwLDAKMjI1MSwyCjIyNTIsMgoyMjUzLDAKMjI1NCwwCjIyNTUsMgoyMjU2LDAKMjI1NywwCjIyNTgsMQoyMjU5LDIKMjI2MCwwCjIyNjEsMgoyMjYyLDEKMjI2MywxCjIyNjQsMAoyMjY1LDAKMjI2NiwwCjIyNjcsMAoyMjY4LDAKMjI2OSwwCjIyNzAsMgoyMjcxLDAKMjI3MiwwCjIyNzMsMgoyMjc0LDEKMjI3NSwwCjIyNzYsMgoyMjc3LDAKMjI3OCwyCjIyNzksMAoyMjgwLDIKMjI4MSwwCjIyODIsMAoyMjgzLDAKMjI4NCwyCjIyODUsMAoyMjg2LDAKMjI4NywwCjIyODgsMQoyMjg5LDIKMjI5MCwyCjIyOTEsMAoyMjkyLDAKMjI5MywwCjIyOTQsMAoyMjk1LDIKMjI5NiwzCjIyOTcsMAoyMjk4LDAKMjI5OSwzCjIzMDAsMgoyMzAxLDIKMjMwMiwxCjIzMDMsMAoyMzA0LDAKMjMwNSwyCjIzMDYsMAoyMzA3LDAKMjMwOCwwCjIzMDksMQoyMzEwLDAKMjMxMSwwCjIzMTIsMQoyMzEzLDAKMjMxNCwwCjIzMTUsMQoyMzE2LDAKMjMxNywyCjIzMTgsMgoyMzE5LDAKMjMyMCwwCjIzMjEsMgoyMzIyLDEKMjMyMywyCjIzMjQsMAoyMzI1LDAKMjMyNiwxCjIzMjcsMAoyMzI4LDIKMjMyOSwwCjIzMzAsMAoyMzMxLDAKMjMzMiwwCjIzMzMsMAoyMzM0LDIKMjMzNSwwCjIzMzYsMQoyMzM3LDAKMjMzOCwwCjIzMzksMAoyMzQwLDAKMjM0MSwyCjIzNDIsMgoyMzQzLDIKMjM0NCwwCjIzNDUsMgoyMzQ2LDIKMjM0NywwCjIzNDgsMAoyMzQ5LDAKMjM1MCwwCjIzNTEsMAoyMzUyLDIKMjM1MywwCjIzNTQsMwoyMzU1LDAKMjM1NiwyCjIzNTcsMAoyMzU4LDAKMjM1OSwwCjIzNjAsMgoyMzYxLDAKMjM2MiwwCjIzNjMsMgoyMzY0LDAKMjM2NSwwCjIzNjYsMQoyMzY3LDAKMjM2OCwwCjIzNjksMQoyMzcwLDMKMjM3MSwwCjIzNzIsMgoyMzczLDEKMjM3NCwwCjIzNzUsMAoyMzc2LDIKMjM3NywxCjIzNzgsMgoyMzc5LDAKMjM4MCwwCjIzODEsMAoyMzgyLDIKMjM4MywyCjIzODQsMAoyMzg1LDIKMjM4NiwyCjIzODcsMAoyMzg4LDAKMjM4OSwwCjIzOTAsMAoyMzkxLDIKMjM5MiwwCjIzOTMsMAoyMzk0LDAKMjM5NSwwCjIzOTYsMAoyMzk3LDAKMjM5OCwzCjIzOTksMAoyNDAwLDAKMjQwMSwwCjI0MDIsMwoyNDAzLDAKMjQwNCwwCjI0MDUsMgoyNDA2LDEKMjQwNywwCjI0MDgsMgoyNDA5LDAKMjQxMCwwCjI0MTEsMQoyNDEyLDAKMjQxMywwCjI0MTQsMgoyNDE1LDEKMjQxNiwwCjI0MTcsMgoyNDE4LDAKMjQxOSwyCjI0MjAsMAoyNDIxLDAKMjQyMiwwCjI0MjMsMAoyNDI0LDAKMjQyNSwyCjI0MjYsMAoyNDI3LDIKMjQyOCwyCjI0MjksMAoyNDMwLDIKMjQzMSwwCjI0MzIsMgoyNDMzLDIKMjQzNCwyCjI0MzUsMQoyNDM2LDAKMjQzNywwCjI0MzgsMQoyNDM5LDAKMjQ0MCwwCjI0NDEsMAoyNDQyLDIKMjQ0MywxCjI0NDQsMwoyNDQ1LDIKMjQ0NiwwCjI0NDcsMAoyNDQ4LDIKMjQ0OSwwCjI0NTAsMAoyNDUxLDIKMjQ1MiwwCjI0NTMsMgoyNDU0LDAKMjQ1NSwwCjI0NTYsMAoyNDU3LDAKMjQ1OCwwCjI0NTksMgoyNDYwLDIKMjQ2MSwyCjI0NjIsMQoyNDYzLDAKMjQ2NCwwCjI0NjUsMAoyNDY2LDEKMjQ2NywwCjI0NjgsMAoyNDY5LDAKMjQ3MCwwCjI0NzEsMAoyNDcyLDAKMjQ3MywyCjI0NzQsMgoyNDc1LDIKMjQ3NiwwCjI0NzcsMgoyNDc4LDAKMjQ3OSwxCjI0ODAsMAoyNDgxLDIKMjQ4MiwwCjI0ODMsMgoyNDg0LDIKMjQ4NSwyCjI0ODYsMgoyNDg3LDAKMjQ4OCwwCjI0ODksMAoyNDkwLDAKMjQ5MSwyCjI0OTIsMgoyNDkzLDAKMjQ5NCwyCjI0OTUsMAoyNDk2LDIKMjQ5NywwCjI0OTgsMAoyNDk5LDAKMjUwMCwyCjI1MDEsMgoyNTAyLDAKMjUwMywwCjI1MDQsMAoyNTA1LDEKMjUwNiwwCjI1MDcsMAoyNTA4LDAKMjUwOSwwCjI1MTAsMAoyNTExLDAKMjUxMiwwCjI1MTMsMAoyNTE0LDAKMjUxNSwwCjI1MTYsMAoyNTE3LDEKMjUxOCwyCjI1MTksMgoyNTIwLDIKMjUyMSwxCjI1MjIsMQoyNTIzLDAKMjUyNCwyCjI1MjUsMgoyNTI2LDAKMjUyNywyCjI1MjgsMAoyNTI5LDIKMjUzMCwwCjI1MzEsMAoyNTMyLDIKMjUzMywwCjI1MzQsMAoyNTM1LDAKMjUzNiwyCjI1MzcsMgoyNTM4LDAKMjUzOSwwCjI1NDAsMAoyNTQxLDIKMjU0MiwwCjI1NDMsMAoyNTQ0LDAKMjU0NSwxCjI1NDYsMAoyNTQ3LDIKMjU0OCwwCjI1NDksMgoyNTUwLDAKMjU1MSwwCjI1NTIsMgoyNTUzLDIKMjU1NCwwCjI1NTUsMAoyNTU2LDAKMjU1NywyCjI1NTgsMQoyNTU5LDEKMjU2MCwwCjI1NjEsMgoyNTYyLDAKMjU2MywyCjI1NjQsMgoyNTY1LDAKMjU2NiwyCjI1NjcsMAoyNTY4LDAKMjU2OSwwCjI1NzAsMQoyNTcxLDAKMjU3MiwyCjI1NzMsMgoyNTc0LDAKMjU3NSwwCjI1NzYsMAoyNTc3LDEKMjU3OCwwCjI1NzksMAoyNTgwLDIKMjU4MSwwCjI1ODIsMgoyNTgzLDAKMjU4NCwwCjI1ODUsMAoyNTg2LDAKMjU4NywwCjI1ODgsMgoyNTg5LDEKMjU5MCwwCjI1OTEsMgoyNTkyLDAKMjU5MywwCjI1OTQsMgoyNTk1LDAKMjU5NiwwCjI1OTcsMgoyNTk4LDIKMjU5OSwwCjI2MDAsMAoyNjAxLDAKMjYwMiwwCjI2MDMsMAoyNjA0LDAKMjYwNSwyCjI2MDYsMwoyNjA3LDAKMjYwOCwwCjI2MDksMAoyNjEwLDAKMjYxMSwyCjI2MTIsMAoyNjEzLDIKMjYxNCwyCjI2MTUsMAoyNjE2LDAKMjYxNywyCjI2MTgsMgoyNjE5LDIKMjYyMCwxCjI2MjEsMgoyNjIyLDAKMjYyMywyCjI2MjQsMAoyNjI1LDAKMjYyNiwzCjI2MjcsMwoyNjI4LDAKMjYyOSwxCjI2MzAsMAoyNjMxLDAKMjYzMiwyCjI2MzMsMAoyNjM0LDIKMjYzNSwyCjI2MzYsMAoyNjM3LDAKMjYzOCwxCjI2MzksMAoyNjQwLDAKMjY0MSwxCjI2NDIsMAoyNjQzLDAKMjY0NCwwCjI2NDUsMgoyNjQ2LDAKMjY0NywwCjI2NDgsMAoyNjQ5LDIKMjY1MCwwCjI2NTEsMAoyNjUyLDIKMjY1MywxCjI2NTQsMgoyNjU1LDAKMjY1NiwwCjI2NTcsMAoyNjU4LDIKMjY1OSwyCjI2NjAsMQoyNjYxLDAKMjY2MiwwCjI2NjMsMgoyNjY0LDAKMjY2NSwyCjI2NjYsMAoyNjY3LDAKMjY2OCwwCjI2NjksMgoyNjcwLDAKMjY3MSwwCjI2NzIsMAoyNjczLDMKMjY3NCwyCjI2NzUsMAoyNjc2LDAKMjY3NywwCjI2NzgsMgoyNjc5LDAKMjY4MCwyCjI2ODEsMAoyNjgyLDAKMjY4MywwCjI2ODQsMgoyNjg1LDIKMjY4NiwwCjI2ODcsMAoyNjg4LDMKMjY4OSwyCjI2OTAsMgoyNjkxLDAKMjY5MiwwCjI2OTMsMQoyNjk0LDEKMjY5NSwwCjI2OTYsMAoyNjk3LDAKMjY5OCwwCjI2OTksMAoyNzAwLDAKMjcwMSwyCjI3MDIsMAoyNzAzLDIKMjcwNCwxCjI3MDUsMAoyNzA2LDIKMjcwNywwCjI3MDgsMAoyNzA5LDEKMjcxMCwyCjI3MTEsMAoyNzEyLDIKMjcxMywwCjI3MTQsMAoyNzE1LDAKMjcxNiwyCjI3MTcsMAoyNzE4LDAKMjcxOSwwCjI3MjAsMAoyNzIxLDAKMjcyMiwwCjI3MjMsMgoyNzI0LDAKMjcyNSwwCjI3MjYsMAoyNzI3LDIKMjcyOCwwCjI3MjksMgoyNzMwLDAKMjczMSwyCjI3MzIsMAoyNzMzLDEKMjczNCwxCjI3MzUsMAoyNzM2LDAKMjczNywwCjI3MzgsMAoyNzM5LDIKMjc0MCwwCjI3NDEsMgoyNzQyLDAKMjc0MywwCjI3NDQsMAoyNzQ1LDIKMjc0NiwxCjI3NDcsMAoyNzQ4LDIKMjc0OSwxCjI3NTAsMAoyNzUxLDAKMjc1MiwwCjI3NTMsMAoyNzU0LDAKMjc1NSwyCjI3NTYsMAoyNzU3LDAKMjc1OCwwCjI3NTksMgoyNzYwLDAKMjc2MSwyCjI3NjIsMAoyNzYzLDAKMjc2NCwyCjI3NjUsMAoyNzY2LDIKMjc2NywwCjI3NjgsMAoyNzY5LDAKMjc3MCwwCjI3NzEsMwoyNzcyLDAKMjc3MywwCjI3NzQsMQoyNzc1LDIKMjc3NiwwCjI3NzcsMAoyNzc4LDIKMjc3OSwwCjI3ODAsMQoyNzgxLDIKMjc4MiwwCjI3ODMsMAoyNzg0LDIKMjc4NSwxCjI3ODYsMAoyNzg3LDAKMjc4OCwwCjI3ODksMgoyNzkwLDAKMjc5MSwwCjI3OTIsMAoyNzkzLDAKMjc5NCwwCjI3OTUsMAoyNzk2LDIKMjc5NywwCjI3OTgsMAoyNzk5LDAKMjgwMCwxCjI4MDEsMAoyODAyLDIKMjgwMywyCjI4MDQsMQoyODA1LDAKMjgwNiwxCjI4MDcsMgoyODA4LDAKMjgwOSwyCjI4MTAsMQoyODExLDAKMjgxMiwxCjI4MTMsMgoyODE0LDAKMjgxNSwwCjI4MTYsMgoyODE3LDIKMjgxOCwwCjI4MTksMAoyODIwLDIKMjgyMSwyCjI4MjIsMgoyODIzLDAKMjgyNCwwCjI4MjUsMAoyODI2LDAKMjgyNywyCjI4MjgsMAoyODI5LDIKMjgzMCwwCjI4MzEsMQoyODMyLDEKMjgzMywwCjI4MzQsMwoyODM1LDAKMjgzNiwwCjI4MzcsMgoyODM4LDAKMjgzOSwzCjI4NDAsMgoyODQxLDAKMjg0MiwwCjI4NDMsMAoyODQ0LDAKMjg0NSwwCjI4NDYsMgoyODQ3LDAKMjg0OCwwCjI4NDksMAoyODUwLDIKMjg1MSwyCjI4NTIsMAoyODUzLDEKMjg1NCwyCjI4NTUsMAoyODU2LDIKMjg1NywwCjI4NTgsMAoyODU5LDIKMjg2MCwyCjI4NjEsMQoyODYyLDAKMjg2MywyCjI4NjQsMgoyODY1LDAKMjg2NiwyCjI4NjcsMgoyODY4LDAKMjg2OSwwCjI4NzAsMAoyODcxLDAKMjg3MiwwCjI4NzMsMAoyODc0LDAKMjg3NSwwCjI4NzYsMAoyODc3LDIKMjg3OCwwCjI4NzksMAoyODgwLDIKMjg4MSwwCjI4ODIsMAoyODgzLDAKMjg4NCwyCjI4ODUsMgoyODg2LDEKMjg4NywyCjI4ODgsMQoyODg5LDAKMjg5MCwyCjI4OTEsMgoyODkyLDAKMjg5MywwCjI4OTQsMAoyODk1LDAKMjg5NiwyCjI4OTcsMAoyODk4LDIKMjg5OSwwCjI5MDAsMgoyOTAxLDAKMjkwMiwyCjI5MDMsMgoyOTA0LDAKMjkwNSwyCjI5MDYsMAoyOTA3LDIKMjkwOCwwCjI5MDksMAoyOTEwLDAKMjkxMSwwCjI5MTIsMAoyOTEzLDAKMjkxNCwyCjI5MTUsMgoyOTE2LDIKMjkxNywwCjI5MTgsMAoyOTE5LDIKMjkyMCwwCjI5MjEsMQoyOTIyLDAKMjkyMywwCjI5MjQsMgoyOTI1LDIKMjkyNiwxCjI5MjcsMAoyOTI4LDMKMjkyOSwyCjI5MzAsMAoyOTMxLDAKMjkzMiwwCjI5MzMsMAoyOTM0LDAKMjkzNSwyCjI5MzYsMAoyOTM3LDAKMjkzOCwyCjI5MzksMQoyOTQwLDAKMjk0MSwyCjI5NDIsMAoyOTQzLDIKMjk0NCwwCjI5NDUsMAoyOTQ2LDIKMjk0NywwCjI5NDgsMwoyOTQ5LDIKMjk1MCwyCjI5NTEsMAoyOTUyLDAKMjk1MywxCjI5NTQsMAoyOTU1LDAKMjk1NiwyCjI5NTcsMAoyOTU4LDAKMjk1OSwwCjI5NjAsMAoyOTYxLDAKMjk2MiwwCjI5NjMsMwoyOTY0LDIKMjk2NSwwCjI5NjYsMAoyOTY3LDAKMjk2OCwwCjI5NjksMAoyOTcwLDAKMjk3MSwwCjI5NzIsMgoyOTczLDIKMjk3NCwwCjI5NzUsMAoyOTc2LDEKMjk3NywwCjI5NzgsMAoyOTc5LDAKMjk4MCwwCjI5ODEsMgoyOTgyLDAKMjk4MywwCjI5ODQsMgoyOTg1LDAKMjk4NiwyCjI5ODcsMAoyOTg4LDAKMjk4OSwwCjI5OTAsMAoyOTkxLDAKMjk5MiwwCjI5OTMsMAoyOTk0LDAKMjk5NSwyCjI5OTYsMAoyOTk3LDAKMjk5OCwxCjI5OTksMAozMDAwLDAKMzAwMSwyCjMwMDIsMgozMDAzLDAKMzAwNCwyCjMwMDUsMAozMDA2LDIKMzAwNywwCjMwMDgsMAozMDA5LDAKMzAxMCwwCjMwMTEsMgozMDEyLDAKMzAxMywyCjMwMTQsMwozMDE1LDAKMzAxNiwxCjMwMTcsMQozMDE4LDAKMzAxOSwwCjMwMjAsMQozMDIxLDAKMzAyMiwyCjMwMjMsMAozMDI0LDIKMzAyNSwwCjMwMjYsMgozMDI3LDAKMzAyOCwwCjMwMjksMAozMDMwLDAKMzAzMSwwCjMwMzIsMAozMDMzLDEKMzAzNCwwCjMwMzUsMAozMDM2LDIKMzAzNywwCjMwMzgsMAozMDM5LDMKMzA0MCwyCjMwNDEsMAozMDQyLDAKMzA0MywwCjMwNDQsMwozMDQ1LDAKMzA0NiwyCjMwNDcsMAozMDQ4LDEKMzA0OSwwCjMwNTAsMAozMDUxLDIKMzA1MiwwCjMwNTMsMAozMDU0LDIKMzA1NSwwCjMwNTYsMAozMDU3LDIKMzA1OCwwCjMwNTksMAozMDYwLDAKMzA2MSwwCjMwNjIsMAozMDYzLDAKMzA2NCwyCjMwNjUsMAozMDY2LDIKMzA2NywwCjMwNjgsMAozMDY5LDAKMzA3MCwyCjMwNzEsMAozMDcyLDAKMzA3MywxCjMwNzQsMAozMDc1LDEKMzA3NiwyCjMwNzcsMgozMDc4LDIKMzA3OSwyCjMwODAsMAozMDgxLDIKMzA4MiwyCjMwODMsMgozMDg0LDIKMzA4NSwyCjMwODYsMAozMDg3LDIKMzA4OCwyCjMwODksMgozMDkwLDAKMzA5MSwwCjMwOTIsMQozMDkzLDEKMzA5NCwyCjMwOTUsMAozMDk2LDIKMzA5NywyCjMwOTgsMwozMDk5LDAKMzEwMCwwCjMxMDEsMAozMTAyLDAKMzEwMywyCjMxMDQsMAozMTA1LDAKMzEwNiwyCjMxMDcsMAozMTA4LDAKMzEwOSwwCjMxMTAsMgozMTExLDAKMzExMiwyCjMxMTMsMAozMTE0LDAKMzExNSwxCjMxMTYsMAozMTE3LDAKMzExOCwyCjMxMTksMgozMTIwLDAKMzEyMSwzCjMxMjIsMgozMTIzLDAKMzEyNCwyCjMxMjUsMQozMTI2LDIKMzEyNywwCjMxMjgsMAozMTI5LDAKMzEzMCwyCjMxMzEsMAozMTMyLDAKMzEzMywwCjMxMzQsMgozMTM1LDAKMzEzNiwxCjMxMzcsMAozMTM4LDEKMzEzOSwyCjMxNDAsMAozMTQxLDAKMzE0MiwwCjMxNDMsMAozMTQ0LDAKMzE0NSwyCjMxNDYsMgozMTQ3LDAKMzE0OCwwCjMxNDksMgozMTUwLDIKMzE1MSwwCjMxNTIsMAozMTUzLDMKMzE1NCwyCjMxNTUsMAozMTU2LDIKMzE1NywxCjMxNTgsMQozMTU5LDAKMzE2MCwzCjMxNjEsMAozMTYyLDEKMzE2MywxCjMxNjQsMAozMTY1LDAKMzE2NiwyCjMxNjcsMQozMTY4LDMKMzE2OSwwCjMxNzAsMQozMTcxLDAKMzE3MiwwCjMxNzMsMgozMTc0LDAKMzE3NSwxCjMxNzYsMgozMTc3LDAKMzE3OCwxCjMxNzksMAozMTgwLDAKMzE4MSwwCjMxODIsMAozMTgzLDIKMzE4NCwwCjMxODUsMAozMTg2LDEKMzE4NywxCjMxODgsMAozMTg5LDIKMzE5MCwwCjMxOTEsMgozMTkyLDIKMzE5MywwCjMxOTQsMgozMTk1LDIKMzE5NiwwCjMxOTcsMgozMTk4LDAKMzE5OSwyCjMyMDAsMAozMjAxLDAKMzIwMiwyCjMyMDMsMAozMjA0LDAKMzIwNSwwCjMyMDYsMAozMjA3LDAKMzIwOCwwCjMyMDksMAozMjEwLDIKMzIxMSwyCjMyMTIsMAozMjEzLDIKMzIxNCwyCjMyMTUsMgozMjE2LDAKMzIxNywyCjMyMTgsMAozMjE5LDAKMzIyMCwwCjMyMjEsMAozMjIyLDAKMzIyMywyCjMyMjQsMAozMjI1LDIKMzIyNiwwCjMyMjcsMAozMjI4LDIKMzIyOSwyCjMyMzAsMQozMjMxLDIKMzIzMiwyCjMyMzMsMAozMjM0LDAKMzIzNSwxCjMyMzYsMgozMjM3LDAKMzIzOCwwCjMyMzksMgozMjQwLDEKMzI0MSwwCjMyNDIsMQozMjQzLDAKMzI0NCwwCjMyNDUsMgozMjQ2LDAKMzI0NywwCjMyNDgsMAozMjQ5LDAKMzI1MCwwCjMyNTEsMQozMjUyLDAKMzI1MywwCjMyNTQsMAozMjU1LDAKMzI1NiwwCjMyNTcsMQozMjU4LDAKMzI1OSwwCjMyNjAsMAozMjYxLDIKMzI2MiwwCjMyNjMsMAozMjY0LDIKMzI2NSwyCjMyNjYsMgozMjY3LDMKMzI2OCwwCjMyNjksMAozMjcwLDIKMzI3MSwwCjMyNzIsMAozMjczLDAKMzI3NCwyCjMyNzUsMgozMjc2LDAKMzI3NywwCjMyNzgsMAozMjc5LDAKMzI4MCwwCjMyODEsMAozMjgyLDAKMzI4MywwCjMyODQsMQozMjg1LDIKMzI4NiwwCjMyODcsMAozMjg4LDAKMzI4OSwyCjMyOTAsMwozMjkxLDAKMzI5MiwwCjMyOTMsMQozMjk0LDEKMzI5NSwyCjMyOTYsMAozMjk3LDAKMzI5OCwwCjMyOTksMAozMzAwLDIKMzMwMSwyCjMzMDIsMAozMzAzLDIKMzMwNCwyCjMzMDUsMgozMzA2LDAKMzMwNywwCjMzMDgsMgozMzA5LDIKMzMxMCwxCjMzMTEsMAozMzEyLDAKMzMxMywwCjMzMTQsMgozMzE1LDAKMzMxNiwyCjMzMTcsMgozMzE4LDAKMzMxOSwwCjMzMjAsMAozMzIxLDIKMzMyMiwyCjMzMjMsMAozMzI0LDIKMzMyNSwwCjMzMjYsMAozMzI3LDAKMzMyOCwwCjMzMjksMAozMzMwLDEKMzMzMSwyCjMzMzIsMgozMzMzLDAKMzMzNCwyCjMzMzUsMgozMzM2LDEKMzMzNywyCjMzMzgsMgozMzM5LDMKMzM0MCwyCjMzNDEsMAozMzQyLDAKMzM0MywwCjMzNDQsMAozMzQ1LDAKMzM0NiwwCjMzNDcsMgozMzQ4LDIKMzM0OSwxCjMzNTAsMAozMzUxLDAKMzM1MiwyCjMzNTMsMAozMzU0LDAKMzM1NSwyCjMzNTYsMgozMzU3LDIKMzM1OCwyCjMzNTksMAozMzYwLDEKMzM2MSwwCjMzNjIsMwozMzYzLDEKMzM2NCwwCjMzNjUsMgozMzY2LDAKMzM2NywyCjMzNjgsMAozMzY5LDMKMzM3MCwyCjMzNzEsMgozMzcyLDAKMzM3MywwCjMzNzQsMAozMzc1LDIKMzM3NiwyCjMzNzcsMwozMzc4LDAKMzM3OSwyCjMzODAsMAozMzgxLDIKMzM4MiwwCjMzODMsMAozMzg0LDEKMzM4NSwwCjMzODYsMAozMzg3LDIKMzM4OCwwCjMzODksMAozMzkwLDAKMzM5MSwyCjMzOTIsMgozMzkzLDMKMzM5NCwwCjMzOTUsMQozMzk2LDAKMzM5NywwCjMzOTgsMgozMzk5LDAKMzQwMCwwCjM0MDEsMAozNDAyLDAKMzQwMywwCjM0MDQsMAozNDA1LDIKMzQwNiwyCjM0MDcsMAozNDA4LDAKMzQwOSwwCjM0MTAsMgozNDExLDAKMzQxMiwyCjM0MTMsMAozNDE0LDAKMzQxNSwwCjM0MTYsMwozNDE3LDAKMzQxOCwyCjM0MTksMQozNDIwLDIKMzQyMSwwCjM0MjIsMgozNDIzLDEKMzQyNCwzCjM0MjUsMAozNDI2LDEKMzQyNywyCjM0MjgsMgozNDI5LDAKMzQzMCwwCjM0MzEsMgozNDMyLDEKMzQzMywwCjM0MzQsMAozNDM1LDEKMzQzNiwyCjM0MzcsMgozNDM4LDIKMzQzOSwyCjM0NDAsMAozNDQxLDAKMzQ0MiwwCjM0NDMsMwozNDQ0LDAKMzQ0NSwwCjM0NDYsMAozNDQ3LDAKMzQ0OCwwCjM0NDksMAozNDUwLDIKMzQ1MSwwCjM0NTIsMgozNDUzLDEKMzQ1NCwyCjM0NTUsMgozNDU2LDAKMzQ1NywyCjM0NTgsMAozNDU5LDEKMzQ2MCwwCjM0NjEsMAozNDYyLDAKMzQ2MywwCjM0NjQsMgozNDY1LDEKMzQ2NiwyCjM0NjcsMAozNDY4LDAKMzQ2OSwwCjM0NzAsMAozNDcxLDAKMzQ3MiwwCjM0NzMsMAozNDc0LDIKMzQ3NSwwCjM0NzYsMAozNDc3LDAKMzQ3OCwxCjM0NzksMAozNDgwLDIKMzQ4MSwwCjM0ODIsMAozNDgzLDAKMzQ4NCwwCjM0ODUsMgozNDg2LDIKMzQ4NywwCjM0ODgsMAozNDg5LDAKMzQ5MCwyCjM0OTEsMAozNDkyLDAKMzQ5MywyCjM0OTQsMAozNDk1LDAKMzQ5NiwwCjM0OTcsMgozNDk4LDAKMzQ5OSwyCjM1MDAsMgozNTAxLDAKMzUwMiwwCjM1MDMsMAozNTA0LDAKMzUwNSwwCjM1MDYsMAozNTA3LDAKMzUwOCwyCjM1MDksMAozNTEwLDIKMzUxMSwwCjM1MTIsMgozNTEzLDIKMzUxNCwwCjM1MTUsMgozNTE2LDAKMzUxNywwCjM1MTgsMgozNTE5LDIKMzUyMCwwCjM1MjEsMgozNTIyLDAKMzUyMywwCjM1MjQsMAozNTI1LDIKMzUyNiwwCjM1MjcsMgozNTI4LDAKMzUyOSwwCjM1MzAsMgozNTMxLDAKMzUzMiwwCjM1MzMsMAozNTM0LDIKMzUzNSwwCjM1MzYsMgozNTM3LDAKMzUzOCwzCjM1MzksMAozNTQwLDAKMzU0MSwwCjM1NDIsMAozNTQzLDAKMzU0NCwyCjM1NDUsMgozNTQ2LDAKMzU0NywwCjM1NDgsMAozNTQ5LDAKMzU1MCwwCjM1NTEsMAozNTUyLDAKMzU1MywxCjM1NTQsMAozNTU1LDIKMzU1NiwwCjM1NTcsMAozNTU4LDIKMzU1OSwyCjM1NjAsMQozNTYxLDAKMzU2MiwyCjM1NjMsMAozNTY0LDAKMzU2NSwyCjM1NjYsMwozNTY3LDAKMzU2OCwwCjM1NjksMgozNTcwLDAKMzU3MSwyCjM1NzIsMAozNTczLDEKMzU3NCwyCjM1NzUsMAozNTc2LDAKMzU3NywwCjM1NzgsMgozNTc5LDEKMzU4MCwwCjM1ODEsMAozNTgyLDAKMzU4MywyCjM1ODQsMAozNTg1LDAKMzU4NiwwCjM1ODcsMgozNTg4LDIKMzU4OSwwCjM1OTAsMgozNTkxLDIKMzU5MiwyCjM1OTMsMAozNTk0LDAKMzU5NSwxCjM1OTYsMgozNTk3LDIKMzU5OCwyCjM1OTksMgozNjAwLDIKMzYwMSwwCjM2MDIsMAozNjAzLDAKMzYwNCwwCjM2MDUsMgozNjA2LDAKMzYwNywxCjM2MDgsMgozNjA5LDAKMzYxMCwyCjM2MTEsMAozNjEyLDAKMzYxMywwCjM2MTQsMAozNjE1LDAKMzYxNiwyCjM2MTcsMAozNjE4LDEKMzYxOSwyCjM2MjAsMAozNjIxLDEKMzYyMiwwCjM2MjMsMAozNjI0LDAKMzYyNSwyCjM2MjYsMgozNjI3LDAKMzYyOCwwCjM2MjksMAozNjMwLDAKMzYzMSwwCjM2MzIsMAozNjMzLDIKMzYzNCwyCjM2MzUsMAozNjM2LDAKMzYzNywwCjM2MzgsMgozNjM5LDAKMzY0MCwyCjM2NDEsMAozNjQyLDAKMzY0MywwCjM2NDQsMAozNjQ1LDAKMzY0NiwyCjM2NDcsMAozNjQ4LDAKMzY0OSwwCjM2NTAsMAozNjUxLDAKMzY1MiwwCjM2NTMsMAozNjU0LDIKMzY1NSwyCjM2NTYsMAozNjU3LDIKMzY1OCwwCjM2NTksMAozNjYwLDEKMzY2MSwwCjM2NjIsMAozNjYzLDAKMzY2NCwzCjM2NjUsMAozNjY2LDAKMzY2NywwCjM2NjgsMAozNjY5LDIKMzY3MCwwCjM2NzEsMAozNjcyLDAKMzY3MywxCjM2NzQsMgozNjc1LDAKMzY3NiwwCjM2NzcsMAozNjc4LDAKMzY3OSwyCjM2ODAsMAozNjgxLDIKMzY4MiwwCjM2ODMsMAozNjg0LDAKMzY4NSwwCjM2ODYsMAozNjg3LDMKMzY4OCwxCjM2ODksMQozNjkwLDAKMzY5MSwxCjM2OTIsMQozNjkzLDAKMzY5NCwwCjM2OTUsMAozNjk2LDAKMzY5NywwCjM2OTgsMAozNjk5LDIKMzcwMCwzCjM3MDEsMAozNzAyLDIKMzcwMywwCjM3MDQsMgozNzA1LDIKMzcwNiwxCjM3MDcsMAozNzA4LDAKMzcwOSwxCjM3MTAsMAozNzExLDIKMzcxMiwwCjM3MTMsMQozNzE0LDAKMzcxNSwyCjM3MTYsMAozNzE3LDAKMzcxOCwwCjM3MTksMQozNzIwLDIKMzcyMSwyCjM3MjIsMAozNzIzLDAKMzcyNCwwCjM3MjUsMgozNzI2LDIKMzcyNywwCjM3MjgsMgozNzI5LDIKMzczMCwwCjM3MzEsMAozNzMyLDAKMzczMywxCjM3MzQsMAozNzM1LDIKMzczNiwwCjM3MzcsMQozNzM4LDAKMzczOSwwCjM3NDAsMAozNzQxLDIKMzc0MiwwCjM3NDMsMwozNzQ0LDIKMzc0NSwwCjM3NDYsMAozNzQ3LDAKMzc0OCwwCjM3NDksMAozNzUwLDAKMzc1MSwwCjM3NTIsMgozNzUzLDAKMzc1NCwyCjM3NTUsMQozNzU2LDAKMzc1NywxCjM3NTgsMgozNzU5LDAKMzc2MCwzCjM3NjEsMgozNzYyLDAKMzc2MywyCjM3NjQsMwozNzY1LDEKMzc2NiwwCjM3NjcsMAozNzY4LDMKMzc2OSwwCjM3NzAsMAozNzcxLDAKMzc3MiwwCjM3NzMsMAozNzc0LDAKMzc3NSwwCjM3NzYsMAozNzc3LDIKMzc3OCwxCjM3NzksMgozNzgwLDAKMzc4MSwwCjM3ODIsMAozNzgzLDAKMzc4NCwwCjM3ODUsMAozNzg2LDIKMzc4NywyCjM3ODgsMAozNzg5LDIKMzc5MCwwCjM3OTEsMgozNzkyLDAKMzc5MywwCjM3OTQsMAozNzk1LDAKMzc5NiwxCjM3OTcsMgozNzk4LDAKMzc5OSwwCjM4MDAsMAozODAxLDAKMzgwMiwxCjM4MDMsMAozODA0LDAKMzgwNSwwCjM4MDYsMQozODA3LDIKMzgwOCwyCjM4MDksMgozODEwLDAKMzgxMSwwCjM4MTIsMAozODEzLDAKMzgxNCwwCjM4MTUsMwozODE2LDAKMzgxNywyCjM4MTgsMgozODE5LDAKMzgyMCwwCjM4MjEsMAozODIyLDEKMzgyMywyCjM4MjQsMgozODI1LDIKMzgyNiwyCjM4MjcsMAozODI4LDAKMzgyOSwxCjM4MzAsMAozODMxLDEKMzgzMiwxCjM4MzMsMAozODM0LDIKMzgzNSwwCjM4MzYsMwozODM3LDAKMzgzOCwyCjM4MzksMAozODQwLDIKMzg0MSwwCjM4NDIsMgozODQzLDAKMzg0NCwwCjM4NDUsMAozODQ2LDEKMzg0NywxCjM4NDgsMAozODQ5LDMKMzg1MCwyCjM4NTEsMAozODUyLDAKMzg1MywwCjM4NTQsMgozODU1LDIKMzg1NiwwCjM4NTcsMAozODU4LDAKMzg1OSwwCjM4NjAsMAozODYxLDIKMzg2MiwyCjM4NjMsMgozODY0LDAKMzg2NSwxCjM4NjYsMgozODY3LDIKMzg2OCwwCjM4NjksMAozODcwLDIKMzg3MSwzCjM4NzIsMAozODczLDIKMzg3NCwwCjM4NzUsMAozODc2LDIKMzg3NywzCjM4NzgsMAozODc5LDAKMzg4MCwwCjM4ODEsMgozODgyLDIKMzg4MywzCjM4ODQsMAozODg1LDAKMzg4NiwyCjM4ODcsMAozODg4LDAKMzg4OSwwCjM4OTAsMAozODkxLDAKMzg5MiwyCjM4OTMsMQozODk0LDAKMzg5NSwyCjM4OTYsMAozODk3LDAKMzg5OCwwCjM4OTksMQozOTAwLDAKMzkwMSwwCjM5MDIsMAozOTAzLDIKMzkwNCwxCjM5MDUsMAozOTA2LDIKMzkwNywwCjM5MDgsMAozOTA5LDAKMzkxMCwwCjM5MTEsMAozOTEyLDAKMzkxMywwCjM5MTQsMQozOTE1LDAKMzkxNiwwCjM5MTcsMwozOTE4LDIKMzkxOSwwCjM5MjAsMAozOTIxLDAKMzkyMiwwCjM5MjMsMAozOTI0LDIKMzkyNSwwCjM5MjYsMgozOTI3LDAKMzkyOCwwCjM5MjksMAozOTMwLDAKMzkzMSwwCjM5MzIsMAozOTMzLDEKMzkzNCwwCjM5MzUsMAozOTM2LDAKMzkzNywwCjM5MzgsMAozOTM5LDAKMzk0MCwwCjM5NDEsMAozOTQyLDIKMzk0MywwCjM5NDQsMQozOTQ1LDIKMzk0NiwwCjM5NDcsMAozOTQ4LDAKMzk0OSwyCjM5NTAsMAozOTUxLDAKMzk1MiwwCjM5NTMsMgozOTU0LDAKMzk1NSwwCjM5NTYsMAozOTU3LDAKMzk1OCwwCjM5NTksMwozOTYwLDAKMzk2MSwyCjM5NjIsMwozOTYzLDIKMzk2NCwxCjM5NjUsMAozOTY2LDIKMzk2NywyCjM5NjgsMgozOTY5LDAKMzk3MCwwCjM5NzEsMAozOTcyLDAKMzk3MywwCjM5NzQsMAozOTc1LDIKMzk3NiwwCjM5NzcsMgozOTc4LDAKMzk3OSwyCjM5ODAsMAozOTgxLDIKMzk4MiwwCjM5ODMsMAozOTg0LDEKMzk4NSwxCjM5ODYsMAozOTg3LDAKMzk4OCwwCjM5ODksMQozOTkwLDAKMzk5MSwwCjM5OTIsMgozOTkzLDIKMzk5NCwyCjM5OTUsMgozOTk2LDAKMzk5NywwCjM5OTgsMAozOTk5LDAKNDAwMCwwCjQwMDEsMgo0MDAyLDIKNDAwMywwCjQwMDQsMAo0MDA1LDAKNDAwNiwyCjQwMDcsMgo0MDA4LDAKNDAwOSwwCjQwMTAsMAo0MDExLDAKNDAxMiwwCjQwMTMsMAo0MDE0LDEKNDAxNSwyCjQwMTYsMAo0MDE3LDEKNDAxOCwwCjQwMTksMAo0MDIwLDIKNDAyMSwzCjQwMjIsMAo0MDIzLDAKNDAyNCwwCjQwMjUsMgo0MDI2LDAKNDAyNywwCjQwMjgsMAo0MDI5LDAKNDAzMCwyCjQwMzEsMAo0MDMyLDEKNDAzMywxCjQwMzQsMAo0MDM1LDAKNDAzNiwwCjQwMzcsMAo0MDM4LDAKNDAzOSwwCjQwNDAsMgo0MDQxLDAKNDA0MiwwCjQwNDMsMgo0MDQ0LDIKNDA0NSwxCjQwNDYsMgo0MDQ3LDIKNDA0OCwwCjQwNDksMAo0MDUwLDIKNDA1MSwyCjQwNTIsMAo0MDUzLDAKNDA1NCwwCjQwNTUsMgo0MDU2LDAKNDA1NywwCjQwNTgsMAo0MDU5LDIKNDA2MCwwCjQwNjEsMgo0MDYyLDAKNDA2MywwCjQwNjQsMAo0MDY1LDIKNDA2NiwwCjQwNjcsMgo0MDY4LDAKNDA2OSwwCjQwNzAsMgo0MDcxLDAKNDA3MiwwCjQwNzMsMgo0MDc0LDIKNDA3NSwwCjQwNzYsMAo0MDc3LDAKNDA3OCwwCjQwNzksMAo0MDgwLDIKNDA4MSwwCjQwODIsMAo0MDgzLDIKNDA4NCwwCjQwODUsMgo0MDg2LDEKNDA4NywwCjQwODgsMgo0MDg5LDEKNDA5MCwwCjQwOTEsMAo0MDkyLDAKNDA5MywwCjQwOTQsMgo0MDk1LDAKNDA5NiwwCjQwOTcsMgo0MDk4LDAKNDA5OSwwCjQxMDAsMgo0MTAxLDAKNDEwMiwyCjQxMDMsMgo0MTA0LDAKNDEwNSwwCjQxMDYsMAo0MTA3LDIKNDEwOCwwCjQxMDksMAo0MTEwLDAKNDExMSwwCjQxMTIsMQo0MTEzLDIKNDExNCwxCjQxMTUsMAo0MTE2LDEKNDExNywwCjQxMTgsMgo0MTE5LDIKNDEyMCwxCjQxMjEsMAo0MTIyLDAKNDEyMywwCjQxMjQsMAo0MTI1LDAKNDEyNiwwCjQxMjcsMAo0MTI4LDAKNDEyOSwwCjQxMzAsMAo0MTMxLDAKNDEzMiwwCjQxMzMsMAo0MTM0LDAKNDEzNSwwCjQxMzYsMAo0MTM3LDAKNDEzOCwwCjQxMzksMAo0MTQwLDEKNDE0MSwyCjQxNDIsMAo0MTQzLDIKNDE0NCwwCjQxNDUsMgo0MTQ2LDAKNDE0NywyCjQxNDgsMQo0MTQ5LDAKNDE1MCwwCjQxNTEsMAo0MTUyLDIKNDE1MywwCjQxNTQsMgo0MTU1LDAKNDE1NiwwCjQxNTcsMAo0MTU4LDIKNDE1OSwxCjQxNjAsMgo0MTYxLDIKNDE2MiwyCjQxNjMsMAo0MTY0LDAKNDE2NSwyCjQxNjYsMAo0MTY3LDIKNDE2OCwwCjQxNjksMAo0MTcwLDEKNDE3MSwzCjQxNzIsMAo0MTczLDIKNDE3NCwwCjQxNzUsMgo0MTc2LDIKNDE3NywwCjQxNzgsMAo0MTc5LDMKNDE4MCwwCjQxODEsMAo0MTgyLDIKNDE4MywxCjQxODQsMQo0MTg1LDAKNDE4NiwyCjQxODcsMAo0MTg4LDIKNDE4OSwwCjQxOTAsMAo0MTkxLDAKNDE5MiwzCjQxOTMsMAo0MTk0LDAKNDE5NSwxCjQxOTYsMAo0MTk3LDAKNDE5OCwwCjQxOTksMAo0MjAwLDAKNDIwMSwwCjQyMDIsMgo0MjAzLDIKNDIwNCwxCjQyMDUsMAo0MjA2LDAKNDIwNywyCjQyMDgsMQo0MjA5LDAKNDIxMCwyCjQyMTEsMwo0MjEyLDIKNDIxMywwCjQyMTQsMAo0MjE1LDAKNDIxNiwwCjQyMTcsMAo0MjE4LDIKNDIxOSwyCjQyMjAsMAo0MjIxLDAKNDIyMiwxCjQyMjMsMAo0MjI0LDAKNDIyNSwwCjQyMjYsMgo0MjI3LDAKNDIyOCwwCjQyMjksMgo0MjMwLDIKNDIzMSwwCjQyMzIsMwo0MjMzLDAKNDIzNCwwCjQyMzUsMgo0MjM2LDAKNDIzNywxCjQyMzgsMQo0MjM5LDMKNDI0MCwyCjQyNDEsMAo0MjQyLDIKNDI0MywyCjQyNDQsMAo0MjQ1LDAKNDI0NiwwCjQyNDcsMgo0MjQ4LDIKNDI0OSwyCjQyNTAsMAo0MjUxLDIKNDI1MiwwCjQyNTMsMAo0MjU0LDAKNDI1NSwwCjQyNTYsMAo0MjU3LDEKNDI1OCwwCjQyNTksMAo0MjYwLDAKNDI2MSwyCjQyNjIsMgo0MjYzLDAKNDI2NCwwCjQyNjUsMAo0MjY2LDAKNDI2NywwCjQyNjgsMAo0MjY5LDEKNDI3MCwwCjQyNzEsMAo0MjcyLDAKNDI3MywyCjQyNzQsMgo0Mjc1LDAKNDI3NiwxCjQyNzcsMQo0Mjc4LDIKNDI3OSwwCjQyODAsMAo0MjgxLDIKNDI4MiwwCjQyODMsMAo0Mjg0LDAKNDI4NSwwCjQyODYsMAo0Mjg3LDAKNDI4OCwzCjQyODksMgo0MjkwLDIKNDI5MSwwCjQyOTIsMAo0MjkzLDAKNDI5NCwyCjQyOTUsMAo0Mjk2LDAKNDI5NywwCjQyOTgsMAo0Mjk5LDAKNDMwMCwwCjQzMDEsMwo0MzAyLDAKNDMwMywwCjQzMDQsMAo0MzA1LDAKNDMwNiwwCjQzMDcsMAo0MzA4LDIKNDMwOSwyCjQzMTAsMgo0MzExLDEKNDMxMiwwCjQzMTMsMAo0MzE0LDMKNDMxNSwwCjQzMTYsMgo0MzE3LDIKNDMxOCwyCjQzMTksMAo0MzIwLDAKNDMyMSwwCjQzMjIsMgo0MzIzLDIKNDMyNCwwCjQzMjUsMAo0MzI2LDEKNDMyNywwCjQzMjgsMQo0MzI5LDAKNDMzMCwwCjQzMzEsMAo0MzMyLDIKNDMzMywwCjQzMzQsMAo0MzM1LDAKNDMzNiwzCjQzMzcsMgo0MzM4LDAKNDMzOSwwCjQzNDAsMAo0MzQxLDMKNDM0MiwwCjQzNDMsMAo0MzQ0LDIKNDM0NSwwCjQzNDYsMAo0MzQ3LDAKNDM0OCwwCjQzNDksMgo0MzUwLDIKNDM1MSwwCjQzNTIsMAo0MzUzLDAKNDM1NCwwCjQzNTUsMgo0MzU2LDAKNDM1NywwCjQzNTgsMAo0MzU5LDAKNDM2MCwwCjQzNjEsMgo0MzYyLDIKNDM2MywyCjQzNjQsMgo0MzY1LDAKNDM2NiwwCjQzNjcsMgo0MzY4LDIKNDM2OSwwCjQzNzAsMgo0MzcxLDAKNDM3MiwwCjQzNzMsMAo0Mzc0LDIKNDM3NSwyCjQzNzYsMAo0Mzc3LDEKNDM3OCwwCjQzNzksMgo0MzgwLDAKNDM4MSwwCjQzODIsMAo0MzgzLDAKNDM4NCwwCjQzODUsMAo0Mzg2LDAKNDM4NywyCjQzODgsMgo0Mzg5LDIKNDM5MCwyCjQzOTEsMAo0MzkyLDAKNDM5MywxCjQzOTQsMAo0Mzk1LDIKNDM5NiwxCjQzOTcsMgo0Mzk4LDAKNDM5OSwyCjQ0MDAsMgo0NDAxLDAKNDQwMiwwCjQ0MDMsMgo0NDA0LDAKNDQwNSwwCjQ0MDYsMAo0NDA3LDIKNDQwOCwyCjQ0MDksMAo0NDEwLDIKNDQxMSwwCjQ0MTIsMgo0NDEzLDAKNDQxNCwxCjQ0MTUsMAo0NDE2LDAKNDQxNywwCjQ0MTgsMgo0NDE5LDIKNDQyMCwwCjQ0MjEsMgo0NDIyLDMKNDQyMywyCjQ0MjQsMAo0NDI1LDAKNDQyNiwwCjQ0MjcsMAo0NDI4LDAKNDQyOSwzCjQ0MzAsMAo0NDMxLDAKNDQzMiwxCjQ0MzMsMgo0NDM0LDAKNDQzNSwyCjQ0MzYsMwo0NDM3LDIKNDQzOCwwCjQ0MzksMgo0NDQwLDEKNDQ0MSwwCjQ0NDIsMgo0NDQzLDAKNDQ0NCwyCjQ0NDUsMgo0NDQ2LDAKNDQ0NywxCjQ0NDgsMQo0NDQ5LDIKNDQ1MCwyCjQ0NTEsMAo0NDUyLDAKNDQ1MywwCjQ0NTQsMAo0NDU1LDAKNDQ1NiwyCjQ0NTcsMgo0NDU4LDAKNDQ1OSwwCjQ0NjAsMAo0NDYxLDAKNDQ2MiwyCjQ0NjMsMAo0NDY0LDIKNDQ2NSwwCjQ0NjYsMAo0NDY3LDIKNDQ2OCwwCjQ0NjksMAo0NDcwLDMKNDQ3MSwwCjQ0NzIsMgo0NDczLDAKNDQ3NCwwCjQ0NzUsMAo0NDc2LDAKNDQ3NywxCjQ0NzgsMgo0NDc5LDAKNDQ4MCwyCjQ0ODEsMAo0NDgyLDIKNDQ4MywxCjQ0ODQsMAo0NDg1LDEKNDQ4NiwwCjQ0ODcsMwo0NDg4LDAKNDQ4OSwxCjQ0OTAsMAo0NDkxLDAKNDQ5MiwzCjQ0OTMsMQo0NDk0LDAKNDQ5NSwyCjQ0OTYsMAo0NDk3LDAKNDQ5OCwwCjQ0OTksMgo0NTAwLDIKNDUwMSwwCjQ1MDIsMAo0NTAzLDIKNDUwNCwwCjQ1MDUsMAo0NTA2LDAKNDUwNywwCjQ1MDgsMAo0NTA5LDEKNDUxMCwyCjQ1MTEsMAo0NTEyLDAKNDUxMywyCjQ1MTQsMgo0NTE1LDIKNDUxNiwyCjQ1MTcsMgo0NTE4LDIKNDUxOSwyCjQ1MjAsMgo0NTIxLDAKNDUyMiwwCjQ1MjMsMAo0NTI0LDEKNDUyNSwwCjQ1MjYsMgo0NTI3LDAKNDUyOCwwCjQ1MjksMAo0NTMwLDAKNDUzMSwwCjQ1MzIsMAo0NTMzLDEKNDUzNCwyCjQ1MzUsMAo0NTM2LDAKNDUzNywyCjQ1MzgsMAo0NTM5LDEKNDU0MCwyCjQ1NDEsMAo0NTQyLDAKNDU0MywyCjQ1NDQsMAo0NTQ1LDMKNDU0NiwyCjQ1NDcsMgo0NTQ4LDIKNDU0OSwwCjQ1NTAsMAo0NTUxLDAKNDU1MiwwCjQ1NTMsMAo0NTU0LDAKNDU1NSwwCjQ1NTYsMgo0NTU3LDIKNDU1OCwwCjQ1NTksMgo0NTYwLDAKNDU2MSwwCjQ1NjIsMgo0NTYzLDIKNDU2NCwwCjQ1NjUsMgo0NTY2LDAKNDU2NywyCjQ1NjgsMQo0NTY5LDIKNDU3MCwyCjQ1NzEsMQo0NTcyLDAKNDU3MywwCjQ1NzQsMAo0NTc1LDAKNDU3NiwyCjQ1NzcsMQo0NTc4LDMKNDU3OSwwCjQ1ODAsMAo0NTgxLDAKNDU4MiwwCjQ1ODMsMAo0NTg0LDAKNDU4NSwwCjQ1ODYsMQo0NTg3LDAKNDU4OCwyCjQ1ODksMAo0NTkwLDAKNDU5MSwwCjQ1OTIsMAo0NTkzLDAKNDU5NCwxCjQ1OTUsMgo0NTk2LDIKNDU5NywyCjQ1OTgsMAo0NTk5LDAKNDYwMCwyCjQ2MDEsMAo0NjAyLDIKNDYwMywwCjQ2MDQsMgo0NjA1LDEKNDYwNiwxCjQ2MDcsMgo0NjA4LDAKNDYwOSwyCjQ2MTAsMAo0NjExLDIKNDYxMiwwCjQ2MTMsMAo0NjE0LDIKNDYxNSwyCjQ2MTYsMAo0NjE3LDIKNDYxOCwyCjQ2MTksMQo0NjIwLDAKNDYyMSwwCjQ2MjIsMgo0NjIzLDIKNDYyNCwwCjQ2MjUsMAo0NjI2LDIKNDYyNywwCjQ2MjgsMAo0NjI5LDIKNDYzMCwyCjQ2MzEsMgo0NjMyLDMKNDYzMywyCjQ2MzQsMAo0NjM1LDMKNDYzNiwxCjQ2MzcsMAo0NjM4LDAKNDYzOSwwCjQ2NDAsMwo0NjQxLDIKNDY0MiwwCjQ2NDMsMAo0NjQ0LDIKNDY0NSwyCjQ2NDYsMgo0NjQ3LDIKNDY0OCwxCjQ2NDksMAo0NjUwLDIKNDY1MSwyCjQ2NTIsMAo0NjUzLDIKNDY1NCwwCjQ2NTUsMAo0NjU2LDAKNDY1NywyCjQ2NTgsMAo0NjU5LDAKNDY2MCwyCjQ2NjEsMgo0NjYyLDAKNDY2MywwCjQ2NjQsMQo0NjY1LDAKNDY2NiwwCjQ2NjcsMgo0NjY4LDIKNDY2OSwzCjQ2NzAsMAo0NjcxLDAKNDY3MiwzCjQ2NzMsMAo0Njc0LDAKNDY3NSwwCjQ2NzYsMAo0Njc3LDAKNDY3OCwyCjQ2NzksMAo0NjgwLDAKNDY4MSwyCjQ2ODIsMAo0NjgzLDAKNDY4NCwyCjQ2ODUsMgo0Njg2LDAKNDY4NywwCjQ2ODgsMAo0Njg5LDAKNDY5MCwwCjQ2OTEsMAo0NjkyLDMKNDY5MywyCjQ2OTQsMgo0Njk1LDAKNDY5NiwyCjQ2OTcsMQo0Njk4LDEKNDY5OSwwCjQ3MDAsMgo0NzAxLDIKNDcwMiwwCjQ3MDMsMAo0NzA0LDAKNDcwNSwwCjQ3MDYsMAo0NzA3LDAKNDcwOCwyCjQ3MDksMAo0NzEwLDIKNDcxMSwwCjQ3MTIsMgo0NzEzLDAKNDcxNCwwCjQ3MTUsMQo0NzE2LDEKNDcxNywwCjQ3MTgsMgo0NzE5LDAKNDcyMCwwCjQ3MjEsMgo0NzIyLDEKNDcyMywwCjQ3MjQsMwo0NzI1LDAKNDcyNiwxCjQ3MjcsMgo0NzI4LDAKNDcyOSwwCjQ3MzAsMAo0NzMxLDIKNDczMiwwCjQ3MzMsMAo0NzM0LDIKNDczNSwwCjQ3MzYsMAo0NzM3LDEKNDczOCwwCjQ3MzksMgo0NzQwLDIKNDc0MSwyCjQ3NDIsMwo0NzQzLDIKNDc0NCwwCjQ3NDUsMAo0NzQ2LDIKNDc0NywyCjQ3NDgsMgo0NzQ5LDEKNDc1MCwwCjQ3NTEsMAo0NzUyLDIKNDc1MywyCjQ3NTQsMgo0NzU1LDAKNDc1NiwwCjQ3NTcsMAo0NzU4LDAKNDc1OSwyCjQ3NjAsMgo0NzYxLDAKNDc2MiwxCjQ3NjMsMAo0NzY0LDAKNDc2NSwyCjQ3NjYsMAo0NzY3LDIKNDc2OCwwCjQ3NjksMAo0NzcwLDMKNDc3MSwyCjQ3NzIsMAo0NzczLDAKNDc3NCwwCjQ3NzUsMAo0Nzc2LDIKNDc3NywwCjQ3NzgsMQo0Nzc5LDAKNDc4MCwwCjQ3ODEsMgo0NzgyLDAKNDc4MywwCjQ3ODQsMAo0Nzg1LDAKNDc4NiwwCjQ3ODcsMgo0Nzg4LDAKNDc4OSwwCjQ3OTAsMAo0NzkxLDAKNDc5MiwyCjQ3OTMsMAo0Nzk0LDIKNDc5NSwwCjQ3OTYsMAo0Nzk3LDIKNDc5OCwyCjQ3OTksMAo0ODAwLDAKNDgwMSwyCjQ4MDIsMgo0ODAzLDEKNDgwNCwyCjQ4MDUsMgo0ODA2LDIKNDgwNywwCjQ4MDgsMgo0ODA5LDEKNDgxMCwwCjQ4MTEsMAo0ODEyLDAKNDgxMywwCjQ4MTQsMgo0ODE1LDIKNDgxNiwwCjQ4MTcsMAo0ODE4LDIKNDgxOSwwCjQ4MjAsMQo0ODIxLDAKNDgyMiwwCjQ4MjMsMAo0ODI0LDAKNDgyNSwyCjQ4MjYsMQo0ODI3LDAKNDgyOCwwCjQ4MjksMAo0ODMwLDIKNDgzMSwwCjQ4MzIsMAo0ODMzLDMKNDgzNCwwCjQ4MzUsMAo0ODM2LDAKNDgzNywwCjQ4MzgsMAo0ODM5LDAKNDg0MCwwCjQ4NDEsMAo0ODQyLDAKNDg0MywwCjQ4NDQsMgo0ODQ1LDAKNDg0NiwwCjQ4NDcsMgo0ODQ4LDAKNDg0OSwwCjQ4NTAsMQo0ODUxLDIKNDg1MiwwCjQ4NTMsMAo0ODU0LDAKNDg1NSwwCjQ4NTYsMAo0ODU3LDEKNDg1OCwwCjQ4NTksMAo0ODYwLDIKNDg2MSwyCjQ4NjIsMgo0ODYzLDIKNDg2NCwwCjQ4NjUsMAo0ODY2LDAKNDg2NywyCjQ4NjgsMAo0ODY5LDAKNDg3MCwwCjQ4NzEsMgo0ODcyLDIKNDg3MywyCjQ4NzQsMAo0ODc1LDAKNDg3NiwwCjQ4NzcsMAo0ODc4LDAKNDg3OSwwCjQ4ODAsMgo0ODgxLDAKNDg4MiwyCjQ4ODMsMwo0ODg0LDIKNDg4NSwxCjQ4ODYsMAo0ODg3LDIKNDg4OCwwCjQ4ODksMgo0ODkwLDIKNDg5MSwwCjQ4OTIsMAo0ODkzLDAKNDg5NCwyCjQ4OTUsMAo0ODk2LDAKNDg5NywwCjQ4OTgsMAo0ODk5LDAKNDkwMCwyCjQ5MDEsMQo0OTAyLDIKNDkwMywwCjQ5MDQsMwo0OTA1LDIKNDkwNiwyCjQ5MDcsMwo0OTA4LDIKNDkwOSwwCjQ5MTAsMgo0OTExLDEKNDkxMiwwCjQ5MTMsMAo0OTE0LDAKNDkxNSwwCjQ5MTYsMgo0OTE3LDAKNDkxOCwwCjQ5MTksMgo0OTIwLDAKNDkyMSwwCjQ5MjIsMAo0OTIzLDAKNDkyNCwwCjQ5MjUsMAo0OTI2LDAKNDkyNywwCjQ5MjgsMQo0OTI5LDAKNDkzMCwyCjQ5MzEsMAo0OTMyLDAKNDkzMywwCjQ5MzQsMAo0OTM1LDIKNDkzNiwwCjQ5MzcsMQo0OTM4LDIKNDkzOSwyCjQ5NDAsMwo0OTQxLDIKNDk0MiwwCjQ5NDMsMAo0OTQ0LDAKNDk0NSwyCjQ5NDYsMAo0OTQ3LDAKNDk0OCwwCjQ5NDksMAo0OTUwLDMKNDk1MSwyCjQ5NTIsMAo0OTUzLDAKNDk1NCwyCjQ5NTUsMAo0OTU2LDAKNDk1NywyCjQ5NTgsMAo0OTU5LDAKNDk2MCwwCjQ5NjEsMAo0OTYyLDAKNDk2MywyCjQ5NjQsMAo0OTY1LDAKNDk2NiwyCjQ5NjcsMgo0OTY4LDAKNDk2OSwzCjQ5NzAsMAo0OTcxLDEKNDk3MiwyCjQ5NzMsMwo0OTc0LDEKNDk3NSwwCjQ5NzYsMAo0OTc3LDAKNDk3OCwyCjQ5NzksMgo0OTgwLDMKNDk4MSwwCjQ5ODIsMAo0OTgzLDIKNDk4NCwwCjQ5ODUsMAo0OTg2LDAKNDk4NywyCjQ5ODgsMAo0OTg5LDIKNDk5MCwwCjQ5OTEsMAo0OTkyLDAKNDk5MywwCjQ5OTQsMgo0OTk1LDIKNDk5NiwwCjQ5OTcsMAo0OTk4LDIKNDk5OSwwCjUwMDAsMAo1MDAxLDIKNTAwMiwyCjUwMDMsMgo1MDA0LDIKNTAwNSwyCjUwMDYsMAo1MDA3LDAKNTAwOCwyCjUwMDksMgo1MDEwLDIKNTAxMSwwCjUwMTIsMAo1MDEzLDMKNTAxNCwwCjUwMTUsMgo1MDE2LDAKNTAxNywwCjUwMTgsMgo1MDE5LDAKNTAyMCwwCjUwMjEsMAo1MDIyLDAKNTAyMywwCjUwMjQsMAo1MDI1LDIKNTAyNiwwCjUwMjcsMQo1MDI4LDAKNTAyOSwyCjUwMzAsMAo1MDMxLDMKNTAzMiwwCjUwMzMsMgo1MDM0LDAKNTAzNSwwCjUwMzYsMwo1MDM3LDAKNTAzOCwwCjUwMzksMAo1MDQwLDAKNTA0MSwyCjUwNDIsMgo1MDQzLDAKNTA0NCwyCjUwNDUsMAo1MDQ2LDAKNTA0NywwCjUwNDgsMAo1MDQ5LDIKNTA1MCwwCjUwNTEsMQo1MDUyLDIKNTA1MywwCjUwNTQsMgo1MDU1LDAKNTA1NiwyCjUwNTcsMAo1MDU4LDIKNTA1OSwwCjUwNjAsMAo1MDYxLDAKNTA2MiwwCjUwNjMsMAo1MDY0LDEKNTA2NSwwCjUwNjYsMAo1MDY3LDAKNTA2OCwyCjUwNjksMAo1MDcwLDAKNTA3MSwwCjUwNzIsMAo1MDczLDIKNTA3NCwwCjUwNzUsMAo1MDc2LDAKNTA3NywwCjUwNzgsMQo1MDc5LDAKNTA4MCwyCjUwODEsMAo1MDgyLDIKNTA4MywwCjUwODQsMQo1MDg1LDIKNTA4NiwwCjUwODcsMAo1MDg4LDAKNTA4OSwyCjUwOTAsMAo1MDkxLDAKNTA5MiwwCjUwOTMsMAo1MDk0LDEKNTA5NSwwCjUwOTYsMAo1MDk3LDEKNTA5OCwyCjUwOTksMAo1MTAwLDAKNTEwMSwyCjUxMDIsMAo1MTAzLDEKNTEwNCwwCjUxMDUsMAo1MTA2LDAKNTEwNywwCjUxMDgsMAo1MTA5LDAKNTExMCwxCjUxMTEsMgo1MTEyLDMKNTExMywwCjUxMTQsMAo1MTE1LDAKNTExNiwyCg=="
    # decode base64 and decompress y_train_file
    y_train_file = base64.b64decode(y_train_file)
    y_data = torch.tensor(pd.read_csv(io.BytesIO(y_train_file)).drop("id", axis=1).to_numpy().reshape(-1)).long()

    # check that x_data has nans in last position of dimension 1 (last vector of every sequence)
    assert torch.isnan(x_data[:, -1, :]).any()

    # shift data to the right in dimension 1
    x_data = torch.roll(x_data, 1, 1)
    x_data[:, 0, :] = -1000 * torch.ones(75)  # set first vector of every sequence to -1000

    x_data.to(device)
    y_data.to(device)

    # split data
    x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.1, random_state=42)
    # load pytorch model from file 'model.pt'

    # create model
    model = TransformerClassifier()
    # if file exists load
    if os.path.isfile('model_nomedian.pt'):
        model.model.load_state_dict(torch.load('model_nomedian.pt'))
    model.set_validation_data(x_test, y_test)
    # fit model
    model.fit(x_train, y_train)
    # detach from gpu and save model
    model.model.cpu()
    torch.save(model.model.state_dict(), 'model_nomedian.pt')
