name: ML4G_Proj2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1t
  - packaging=23.0
  - pexpect=4.8.0
  - pip=23.0.1
  - ptyprocess=0.7.0
  - python=3.10.10
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - anndata==0.9.1
      - blinker==1.6.2
      - charset-normalizer==3.1.0
      - click==8.1.3
      - community==1.0.0b1
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.34
      - dbscan==0.0.12
      - decorator==5.1.1
      - deprecated==1.2.13
      - flask==2.3.1
      - fonttools==4.39.3
      - future==0.18.3
      - graphtools==1.5.3
      - h5py==3.8.0
      - harmonypy==0.0.9
      - hdbscan==0.8.29
      - idna==3.4
      - igraph==0.10.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - leidenalg==0.9.1
      - llvmlite==0.39.1
      - louvain==0.8.0
      - magic-impute==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - natsort==8.3.1
      - networkx==3.1
      - numba==0.56.4
      - numpy==1.23.5
      - pandas==1.3.5
      - patsy==0.5.3
      - pillow==9.5.0
      - pygsp==0.5.1
      - pynndescent==0.5.10
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-louvain==0.16
      - pytz==2023.3
      - requests==2.29.0
      - saver==0.0.2
      - scanpy==1.9.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - scprep==1.2.2
      - seaborn==0.12.2
      - session-info==1.0.0
      - six==1.16.0
      - statsmodels==0.14.0rc0
      - stdlib-list==0.8.0
      - tasklogger==1.2.0
      - texttable==1.6.7
      - threadpoolctl==3.1.0
      - tqdm==4.65.0
      - tzdata==2023.3
      - umap-learn==0.5.3
      - urllib3==1.26.15
      - werkzeug==2.3.1
      - wrapt==1.15.0
